@echo off
cd /d L:\Website\Manus2
(
echo CREATE TABLE IF NOT EXISTS flashcard_decks (id INT AUTO_INCREMENT PRIMARY KEY, cookieId VARCHAR(128) NOT NULL, userId INT, title VARCHAR(512) NOT NULL, description TEXT, sourceType ENUM('research','manual','ai_generated') DEFAULT 'ai_generated', sourceId INT, cardCount INT DEFAULT 0, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_fc_decks_cookie (cookieId));
echo CREATE TABLE IF NOT EXISTS flashcards (id INT AUTO_INCREMENT PRIMARY KEY, deckId INT NOT NULL, front TEXT NOT NULL, back TEXT NOT NULL, `interval` INT DEFAULT 1, easeFactor FLOAT DEFAULT 2.5, repetitions INT DEFAULT 0, dueDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_fc_deck (deckId), INDEX idx_fc_due (dueDate), INDEX idx_fc_deck_due (deckId, dueDate));
echo CREATE TABLE IF NOT EXISTS flashcard_reviews (id INT AUTO_INCREMENT PRIMARY KEY, cardId INT NOT NULL, deckId INT NOT NULL, cookieId VARCHAR(128) NOT NULL, rating ENUM('again','hard','good','easy') NOT NULL, reviewedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_fcr_deck (deckId), INDEX idx_fcr_cookie (cookieId));
echo CREATE TABLE IF NOT EXISTS ai_provider_settings (id INT AUTO_INCREMENT PRIMARY KEY, cookieId VARCHAR(128) NOT NULL UNIQUE, provider ENUM('gemini','perplexity','openai') DEFAULT 'gemini', apiKey VARCHAR(512), model VARCHAR(128), createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
echo CREATE TABLE IF NOT EXISTS mind_maps (id INT AUTO_INCREMENT PRIMARY KEY, cookieId VARCHAR(128) NOT NULL, userId INT, title VARCHAR(512) NOT NULL, rootTopic VARCHAR(256) NOT NULL, nodesJson JSON, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_mm_cookie (cookieId));
echo CREATE TABLE IF NOT EXISTS library_resources (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(512) NOT NULL, url VARCHAR(1024) NOT NULL, description TEXT NOT NULL, category VARCHAR(128) NOT NULL, tags JSON, difficulty ENUM('beginner','intermediate','advanced') DEFAULT 'intermediate', type ENUM('article','video','course','tool','paper','book','repo') DEFAULT 'article', featured BOOLEAN DEFAULT FALSE, contributedBy VARCHAR(128), ratingSum INT DEFAULT 0, ratingCount INT DEFAULT 0, viewCount INT DEFAULT 0, addedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
echo CREATE TABLE IF NOT EXISTS test_questions (id INT AUTO_INCREMENT PRIMARY KEY, testId VARCHAR(64) NOT NULL, category VARCHAR(64) NOT NULL, question TEXT NOT NULL, options JSON NOT NULL, correctAnswer INT NOT NULL, explanation TEXT, difficulty ENUM('easy','medium','hard') DEFAULT 'medium', questionType VARCHAR(32) DEFAULT 'multiple-choice', imageData TEXT, sortOrder INT DEFAULT 0, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
echo CREATE TABLE IF NOT EXISTS test_results (id INT AUTO_INCREMENT PRIMARY KEY, cookieId VARCHAR(128) NOT NULL, testId VARCHAR(64) NOT NULL, score INT NOT NULL, totalQuestions INT NOT NULL, answers JSON NOT NULL, timeTakenSeconds INT, completedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_tr_cookie (cookieId), INDEX idx_tr_test (testId));
echo CREATE TABLE IF NOT EXISTS iq_results (id INT AUTO_INCREMENT PRIMARY KEY, cookieId VARCHAR(128) NOT NULL, iqScore INT NOT NULL, percentile INT NOT NULL, rawScore INT NOT NULL, categoryScores JSON NOT NULL, timeTakenSeconds INT, completedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_iq_cookie (cookieId));
echo CREATE TABLE IF NOT EXISTS lessons (id INT AUTO_INCREMENT PRIMARY KEY, userId INT, cookieId VARCHAR(128) NOT NULL, curriculumId VARCHAR(64) NOT NULL, title VARCHAR(512) NOT NULL, description TEXT, content TEXT NOT NULL, objectives JSON, keyPoints JSON, resources JSON, externalResources JSON, difficulty ENUM('beginner','intermediate','advanced') DEFAULT 'intermediate', estimatedMinutes INT DEFAULT 15, `order` INT DEFAULT 0, isShared BOOLEAN DEFAULT FALSE, viewCount INT DEFAULT 0, completed BOOLEAN DEFAULT FALSE, completedAt TIMESTAMP NULL, relatedTopics JSON, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_les_cookie (cookieId), INDEX idx_les_curriculum (curriculumId), INDEX idx_les_shared (isShared));
echo CREATE TABLE IF NOT EXISTS lesson_questions (id INT AUTO_INCREMENT PRIMARY KEY, lessonId INT NOT NULL, userId INT, cookieId VARCHAR(128) NOT NULL, question TEXT NOT NULL, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
echo CREATE TABLE IF NOT EXISTS lesson_answers (id INT AUTO_INCREMENT PRIMARY KEY, questionId INT NOT NULL, aiResponse TEXT NOT NULL, helpfulCount INT DEFAULT 0, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
echo CREATE TABLE IF NOT EXISTS lesson_ratings (id INT AUTO_INCREMENT PRIMARY KEY, lessonId INT NOT NULL, userId INT, cookieId VARCHAR(128) NOT NULL, rating INT NOT NULL, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
echo CREATE TABLE IF NOT EXISTS lesson_feedback (id INT AUTO_INCREMENT PRIMARY KEY, lessonId INT NOT NULL, cookieId VARCHAR(128) NOT NULL, feedback TEXT NOT NULL, category ENUM('too_easy','too_hard','unclear','excellent','needs_update','other') DEFAULT 'other', createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
echo CREATE TABLE IF NOT EXISTS lesson_progress (id INT AUTO_INCREMENT PRIMARY KEY, userId INT, cookieId VARCHAR(128) NOT NULL, lessonId INT NOT NULL, startedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, completedAt TIMESTAMP NULL, timeSpentSeconds INT DEFAULT 0, attempts INT DEFAULT 1, lastAccessedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_lp_cl (cookieId, lessonId), INDEX idx_lp_cookie (cookieId));
echo CREATE TABLE IF NOT EXISTS curriculum_progress (id INT AUTO_INCREMENT PRIMARY KEY, userId INT, cookieId VARCHAR(128) NOT NULL, curriculumId VARCHAR(255) NOT NULL, startedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, completedAt TIMESTAMP NULL, lessonsCompleted INT DEFAULT 0, totalLessons INT DEFAULT 0, lastAccessedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_cp_cc (cookieId, curriculumId));
) | C:\mariadb\bin\mysql.exe -u root --protocol=tcp -P 3306 nexus 2>&1
echo Done creating tables.
echo SHOW TABLES; | C:\mariadb\bin\mysql.exe -u root --protocol=tcp -P 3306 nexus 2>&1
