http:
  routers:
    nexus:
      rule: "Host(`schmo.tech`) || Host(`www.schmo.tech`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: nexus-svc

  services:
    nexus-svc:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3000"
