export type FoundationLessonSeed = {
  title: string;
  scenario: string;
  visual: string;
  challenge: string;
  trap: string;
};

export type FoundationModuleSeed = {
  id: string;
  title: string;
  purpose: string;
  outcomes: string[];
  signatureInteractions: string[];
  capstone: string;
  estimatedMinutes: number;
  lessons: FoundationLessonSeed[];
};

export const aiModuleSeeds: FoundationModuleSeed[] = [
  {
    id: "ai-m1",
    title: "Module 1 - What AI Actually Is",
    purpose: "Replace hype and loose buzzwords with a stable mental model of what AI is and is not.",
    outcomes: [
      "Define AI in plain language without sounding vague.",
      "Separate AI from automation and ordinary software.",
      "Explain why headlines overstate what current systems can do.",
    ],
    signatureInteractions: ["Is this really AI?", "Hype vs reality timeline"],
    capstone: "Sort 12 tools and systems into AI, automation, software, or neither and justify each call.",
    estimatedMinutes: 80,
    lessons: [
      {
        title: "The AI confusion problem",
        scenario: "A company labels a simple rules engine as AI because the term sounds modern, and nobody notices the difference.",
        visual: "Confusion map showing buzzword AI, true machine learning, automation, and standard software.",
        challenge: "Collect five products that claim to use AI and classify what each one is actually doing.",
        trap: "Treating every adaptive or digital system as AI.",
      },
      {
        title: "What makes something AI",
        scenario: "Two tools both make recommendations, but only one learned patterns from data instead of following fixed instructions.",
        visual: "Decision frame for prediction, pattern recognition, adaptation, and probabilistic output.",
        challenge: "Explain AI to a non-technical friend using one sentence for data, one for prediction, and one for uncertainty.",
        trap: "Defining AI so broadly that the term loses meaning.",
      },
      {
        title: "AI vs automation vs traditional software",
        scenario: "A manager chooses the wrong vendor because they confuse workflow automation with a model that makes predictions under uncertainty.",
        visual: "Three-lane comparison chart for automation, software, and AI systems.",
        challenge: "Pick one task from your work and argue which approach fits best: fixed rules, workflow automation, or AI.",
        trap: "Assuming AI is always the most advanced or appropriate choice.",
      },
      {
        title: "Narrow AI, AGI, and the reality gap",
        scenario: "A dramatic headline about general intelligence creates fear even though the underlying product is a narrow specialist tool.",
        visual: "Ladder from narrow task systems to speculative general intelligence claims.",
        challenge: "Rewrite one sensational AI headline so it matches what current systems can actually do.",
        trap: "Letting speculation about AGI distort how you judge today's tools.",
      },
      {
        title: "A short history of hype and progress",
        scenario: "A learner thinks the current AI moment came out of nowhere and misses the repeated cycle of inflated claims, disappointment, and real progress.",
        visual: "Timeline of winters, breakthroughs, and product adoption waves.",
        challenge: "Annotate the AI timeline with one lesson about what progress is real and what stays cyclical.",
        trap: "Mistaking short-term excitement for permanent transformation.",
      },
    ],
  },
  {
    id: "ai-m2",
    title: "Module 2 - How AI Works Without the Math Overload",
    purpose: "Give non-specialists a conceptual model for modern AI without drowning them in formulas.",
    outcomes: [
      "Explain data, models, training, and inference in ordinary language.",
      "Describe why AI output is probabilistic rather than magical.",
      "Understand why models can feel smart while still failing badly.",
    ],
    signatureInteractions: ["Build-a-model analogy", "Broken AI pipeline diagnosis"],
    capstone: "Explain how a modern AI system works to a skeptical friend using one analogy and one real example.",
    estimatedMinutes: 85,
    lessons: [
      {
        title: "Data is the diet",
        scenario: "A model behaves strangely in a niche domain because the examples that shaped it did not reflect the real task.",
        visual: "Training diet board linking data quality, coverage, and downstream behavior.",
        challenge: "Choose one AI task and list what kinds of data would make the model stronger or weaker.",
        trap: "Thinking model quality is independent of what the model learned from.",
      },
      {
        title: "What a model is",
        scenario: "A person imagines a model as a database of exact answers when it is really a learned pattern system that predicts likely continuations.",
        visual: "Model-as-pattern-machine illustration rather than a file cabinet of facts.",
        challenge: "Describe the difference between stored facts and learned patterns using one everyday analogy.",
        trap: "Imagining the model as a literal encyclopedia with reliable retrieval.",
      },
      {
        title: "Training vs inference",
        scenario: "A team keeps tweaking prompts to solve a failure that actually comes from missing data, weak training, or retrieval limits.",
        visual: "Factory floor metaphor separating model building, deployment, and live use.",
        challenge: "Diagnose whether three failure cases belong to data, training, retrieval, or prompting.",
        trap: "Blaming the live interaction for every problem in the pipeline.",
      },
      {
        title: "Why AI feels intelligent",
        scenario: "A polished answer sounds thoughtful and original even though it mainly reflects learned language patterns and context steering.",
        visual: "Illusion stack of fluency, speed, confidence, and coherence.",
        challenge: "Build a checklist for separating surface fluency from grounded competence.",
        trap: "Equating eloquence with understanding.",
      },
      {
        title: "Why AI can be confidently wrong",
        scenario: "A model invents a policy detail and states it with complete certainty in a context where the user most needs caution.",
        visual: "Failure path from probability-based completion to fabricated certainty.",
        challenge: "Run a verification pass on an AI answer and mark every claim that needs outside checking.",
        trap: "Treating confidence as a signal of truth.",
      },
    ],
  },
  {
    id: "ai-m3",
    title: "Module 3 - Generative AI and the New Tool Landscape",
    purpose: "Help learners choose the right AI tool and understand what generative systems are actually good at.",
    outcomes: [
      "Differentiate search, chat, and generation.",
      "Recognize major AI product categories.",
      "Match the right type of AI help to the right kind of task.",
    ],
    signatureInteractions: ["Choose the right tool", "Search vs chat vs generate challenge"],
    capstone: "Map 10 realistic tasks to the best AI tool type and defend your reasoning.",
    estimatedMinutes: 80,
    lessons: [
      {
        title: "What generative AI is",
        scenario: "One family of tools can produce text, images, code, and audio, but the risks differ across each output type.",
        visual: "Modality wheel covering text, image, audio, video, and code generation.",
        challenge: "List where generative AI helps you the most today and where its risks change by medium.",
        trap: "Treating all generated outputs as equally reliable.",
      },
      {
        title: "LLMs in plain English",
        scenario: "A learner sees radically different answers from the same model and realizes context and prompt structure shape the output path.",
        visual: "Context window strip showing instructions, examples, retrieved facts, and output shaping.",
        challenge: "Take one vague prompt and improve it by changing only the context and output format.",
        trap: "Thinking the model has one stable answer independent of framing.",
      },
      {
        title: "Search, chat, and generation are not the same",
        scenario: "Someone needs cited facts but uses a generation tool as if it were a search engine and ends up with polished uncertainty.",
        visual: "Decision tree that begins with retrieve, converse, or create.",
        challenge: "For five tasks, decide whether search, chat, or generation should come first and explain why.",
        trap: "Mistaking synthesis for evidence retrieval.",
      },
      {
        title: "Common AI tool categories",
        scenario: "A team buys a general assistant when what they really needed was an analyst or a domain-specific copilot.",
        visual: "Landscape matrix for assistants, copilots, tutors, generators, analysts, and agents.",
        challenge: "Map your current tool stack to the right categories and mark where the fit is poor.",
        trap: "Assuming every AI product solves the same class of problem.",
      },
      {
        title: "Where generative AI is strongest",
        scenario: "A workflow improves dramatically when AI is used for first drafts and pattern synthesis, but degrades when AI is treated as final authority.",
        visual: "Strength radar showing ideation, drafting, transformation, summarization, and pattern synthesis.",
        challenge: "Design a first-draft-plus-human-review workflow for one recurring task.",
        trap: "Using generative AI where final judgment still matters most.",
      },
    ],
  },
  {
    id: "ai-m4",
    title: "Module 4 - Where AI Fails",
    purpose: "Build healthy skepticism and repeatable trust-calibration habits before learners scale their AI use.",
    outcomes: [
      "Spot hallucinations, fake sources, and brittle reasoning.",
      "Recognize bias and context failure.",
      "Use verification workflows before acting on output.",
    ],
    signatureInteractions: ["Spot the hallucination", "Source verification drill", "Trust signal audit"],
    capstone: "Audit one AI-generated answer and annotate every trust signal, warning sign, and missing check.",
    estimatedMinutes: 95,
    lessons: [
      {
        title: "Hallucinations explained",
        scenario: "A meeting memo includes a fabricated policy detail that sounds perfectly plausible and slips past everyone on first read.",
        visual: "Anatomy of a hallucination from ambiguous prompt to polished falsehood.",
        challenge: "Create a hallucination red-flag checklist for your domain.",
        trap: "Assuming polished wording implies grounded truth.",
      },
      {
        title: "Bias in, bias out",
        scenario: "A scoring system seems objective until you notice the data reflected historical exclusion and unequal representation.",
        visual: "Bias pipeline from data collection through deployment feedback loops.",
        challenge: "Run a mini impact assessment on one AI-assisted decision workflow.",
        trap: "Thinking bias only enters at the model layer.",
      },
      {
        title: "Fake sources and invented certainty",
        scenario: "A report includes realistic-looking references that collapse as soon as somebody checks whether the sources even exist.",
        visual: "Citation ladder from claim to source existence to claim-source match.",
        challenge: "Verify three citations from one AI answer and document your pass-fail method.",
        trap: "Treating formatting as proof.",
      },
      {
        title: "Context loss and brittle understanding",
        scenario: "The model handles the obvious case well, but breaks as soon as local rules, edge cases, or conflicting constraints appear.",
        visual: "Context stack showing hidden constraints, edge cases, and missing assumptions.",
        challenge: "Repair a failed AI answer by listing the context it needed but never received.",
        trap: "Assuming the model knows your local rules, values, or exceptions by default.",
      },
      {
        title: "The danger of overtrust",
        scenario: "A manager forwards AI analysis into a decision process without checking the chain of reasoning because the output looks ready to use.",
        visual: "Trust calibration curve from undertrust to calibrated trust to overtrust.",
        challenge: "Write a team norm for when AI outputs require explicit review before action.",
        trap: "Using convenience as a substitute for judgment.",
      },
      {
        title: "Verification workflows",
        scenario: "Two analysts use the same model, but only one catches a bad answer because they follow a simple verification routine every time.",
        visual: "Verification flowchart covering source checks, logic checks, domain checks, and human approval.",
        challenge: "Build your own pre-action verification checklist and test it on one live response.",
        trap: "Treating verification as optional cleanup instead of core workflow.",
      },
    ],
  },
  {
    id: "ai-m5",
    title: "Module 5 - Prompting and Working With AI Well",
    purpose: "Teach collaboration habits that outperform prompt magic and lead to more reliable work.",
    outcomes: [
      "Write stronger prompts with clear constraints and criteria.",
      "Iterate productively instead of relying on one-shot asks.",
      "Prompt for critique, alternatives, and checks rather than only output.",
    ],
    signatureInteractions: ["Rewrite weak prompts", "Prompt style comparison", "Critique-first prompting drill"],
    capstone: "Convert one vague ask into a robust prompt chain with evaluation criteria and review steps.",
    estimatedMinutes: 90,
    lessons: [
      {
        title: "Why bad prompts get bad results",
        scenario: "Two people use the same model, but one gets generic fluff because the request was underspecified.",
        visual: "Prompt quality ladder from vague demand to constrained task brief.",
        challenge: "Take one weak prompt and add task, context, constraints, and success criteria.",
        trap: "Expecting the model to infer goals you never stated.",
      },
      {
        title: "The anatomy of a strong prompt",
        scenario: "A structured request turns a mediocre answer into a usable draft because the model now knows the job and the bar.",
        visual: "Prompt canvas showing task, context, constraints, format, and evaluation criteria.",
        challenge: "Build a reusable prompt template for a task you repeat every week.",
        trap: "Stopping at instructions and forgetting the quality standard.",
      },
      {
        title: "Iteration beats one-shot prompting",
        scenario: "A second and third round produce much stronger reasoning than the original answer because the user asks for revision instead of settling.",
        visual: "Loop diagram of draft, critique, revise, and verify.",
        challenge: "Run a two-iteration prompt cycle and compare the before-and-after quality.",
        trap: "Treating the first draft as the final answer.",
      },
      {
        title: "Prompting for thinking, not just output",
        scenario: "A request for assumptions, counterarguments, and failure modes surfaces risks the first answer hid.",
        visual: "Reasoning prompt deck covering alternatives, assumptions, counterexamples, and checks.",
        challenge: "Refactor one output-only prompt into a reasoning-first prompt.",
        trap: "Optimizing for speed of output instead of depth of thought.",
      },
      {
        title: "Prompting for different tasks",
        scenario: "A writing prompt, planning prompt, and research prompt all need different scaffolds to produce useful work.",
        visual: "Task-to-prompt matrix for writing, planning, study, research, and analysis.",
        challenge: "Create two task-specific prompts and define what success looks like for each.",
        trap: "Using one universal prompt pattern for every kind of work.",
      },
      {
        title: "Prompting ethically and safely",
        scenario: "A user pastes sensitive information into a public tool without realizing the privacy, compliance, and reputation risks.",
        visual: "Safety boundary map separating safe prompting, caution zones, and prohibited use.",
        challenge: "Draft a privacy and safety checklist for prompts used at work.",
        trap: "Assuming speed matters more than privacy, consent, or compliance.",
      },
    ],
  },
  {
    id: "ai-m6",
    title: "Module 6 - AI in Work, Learning, and Everyday Life",
    purpose: "Ground AI literacy in the repeated decisions adults actually face every week.",
    outcomes: [
      "Choose high-value use cases instead of novelty use cases.",
      "Set clear judgment boundaries around AI help.",
      "Know when not to use AI at all.",
    ],
    signatureInteractions: ["Would you use AI here?", "Workflow redesign scenarios"],
    capstone: "Draft a personal AI use policy for work, learning, and home.",
    estimatedMinutes: 80,
    lessons: [
      {
        title: "AI in writing and communication",
        scenario: "A team speeds up drafting with AI, but still needs human ownership of tone, clarity, truth, and responsibility.",
        visual: "Writing workflow from brainstorm to draft to verify to publish.",
        challenge: "Create a communication SOP that separates AI drafting from human sign-off.",
        trap: "Using generated text as if it already reflects your intent and standards.",
      },
      {
        title: "AI in research and learning",
        scenario: "A learner consumes polished summaries but cannot transfer the ideas because the process never required retrieval or application.",
        visual: "Learning stack linking summarize, retrieve, apply, and teach-back.",
        challenge: "Turn one AI summary into a retrieval quiz and a teach-back exercise.",
        trap: "Confusing familiarity with durable understanding.",
      },
      {
        title: "AI at work",
        scenario: "One team redesigns workflows around AI and gains leverage, while another just adds a chatbot and creates rework.",
        visual: "Role redesign map by task repeatability, stakes, and oversight needed.",
        challenge: "Redesign three tasks in one role using AI plus explicit quality gates.",
        trap: "Adding AI without redesigning the surrounding workflow.",
      },
      {
        title: "AI in daily decisions",
        scenario: "An AI plan looks efficient on paper but ignores values, context, and the tradeoffs that matter most to the human deciding.",
        visual: "Decision frame separating objective constraints from personal values.",
        challenge: "Use AI to generate options for one decision, then annotate where your judgment overrides it.",
        trap: "Letting convenience overrule context and values.",
      },
      {
        title: "When not to use AI",
        scenario: "A confident answer in a high-stakes context creates false reassurance where expertise, empathy, or accountability are essential.",
        visual: "Risk map for low-stakes, medium-stakes, and high-stakes AI use.",
        challenge: "Write a red-list of tasks that always require expert review or human-first handling.",
        trap: "Using AI as if all domains have the same error tolerance.",
      },
    ],
  },
  {
    id: "ai-m7",
    title: "Module 7 - Ethics, Society, and Responsibility",
    purpose: "Move ethical discussion beyond slogans into real tradeoffs, incentives, harms, and safeguards.",
    outcomes: [
      "Discuss privacy, labor, bias, and accountability with clarity.",
      "Map stakeholder risks instead of debating only in slogans.",
      "Recommend practical safeguards for real deployments.",
    ],
    signatureInteractions: ["Stakeholder mapping", "Ethics triage", "Safeguard design sprint"],
    capstone: "Evaluate one deployment scenario and recommend governance safeguards that are actually workable.",
    estimatedMinutes: 95,
    lessons: [
      {
        title: "The ethics baseline",
        scenario: "A technically impressive feature creates harm because nobody stopped to ask whether it should exist or what good success even means.",
        visual: "Triangle of capability, consequences, and accountability.",
        challenge: "Build a one-page ethics checklist for an AI feature proposal.",
        trap: "Assuming technical feasibility equals moral permission.",
      },
      {
        title: "Privacy and surveillance",
        scenario: "A convenience feature quietly expands monitoring beyond what users expected or meaningfully consented to.",
        visual: "Data lifecycle map with consent, storage, access, and deletion checkpoints.",
        challenge: "Audit one workflow for unnecessary data collection and retention.",
        trap: "Treating data access as harmless because it is technically possible.",
      },
      {
        title: "Bias, inclusion, and power",
        scenario: "A system works well for majority users but fails the people with the least power to complain or appeal.",
        visual: "Stakeholder power map showing who benefits, who is harmed, and who decides.",
        challenge: "Make a stakeholder map for one AI system and identify who is missing from the room.",
        trap: "Thinking average performance means equitable performance.",
      },
      {
        title: "AI and misinformation",
        scenario: "Synthetic content spreads faster than corrections because fluency, scale, and speed all favor the first convincing story.",
        visual: "Misinformation cascade with intervention points for detection and response.",
        challenge: "Create a protocol for handling suspicious synthetic content in your team or household.",
        trap: "Believing faster content production does not change epistemic risk.",
      },
      {
        title: "Work and economic disruption",
        scenario: "A role does not disappear overnight, but its routine tasks shift and its human value changes faster than the job description does.",
        visual: "Task-shift board showing automate, augment, redesign, and retrain.",
        challenge: "Write a reskilling plan for one role affected by AI.",
        trap: "Thinking disruption is only replacement or only hype.",
      },
      {
        title: "Responsibility and accountability",
        scenario: "An AI-assisted decision goes wrong and everyone points at the model instead of the humans and institutions around it.",
        visual: "Accountability chain from data owners to deployers to decision makers.",
        challenge: "Draft a responsibility map for one AI workflow in your world.",
        trap: "Treating 'the AI did it' as a meaningful accountability answer.",
      },
    ],
  },
  {
    id: "ai-m8",
    title: "Module 8 - Becoming an AI-Native Thinker",
    purpose: "Synthesize the course into a long-term posture that preserves agency while using powerful tools.",
    outcomes: [
      "Build a mature posture toward AI rather than hype or fear.",
      "Turn verification into a durable habit.",
      "Design repeatable AI workflows you would trust in real life.",
    ],
    signatureInteractions: ["Decision framework builder", "Final AI trust checklist", "Workflow stress test"],
    capstone: "Redesign one AI-assisted workflow into a wiser version you would actually trust and defend.",
    estimatedMinutes: 80,
    lessons: [
      {
        title: "A mature posture toward AI",
        scenario: "One person drifts into hype, another into fear, and a third develops disciplined, calibrated competence.",
        visual: "Posture spectrum from fear to hype to grounded confidence.",
        challenge: "Write a three-principle statement that describes your posture toward AI.",
        trap: "Thinking wisdom means either maximal enthusiasm or maximal suspicion.",
      },
      {
        title: "Verification as a habit",
        scenario: "A tiny recurring check prevents a major downstream error because the user designed verification into the workflow instead of relying on memory.",
        visual: "Habit loop showing trigger, check, decision, and review.",
        challenge: "Embed one verification step directly into a task you already do every week.",
        trap: "Treating verification as something you do only when you feel nervous.",
      },
      {
        title: "Building an AI workflow",
        scenario: "A stable draft-critique-verify-refine workflow beats ad hoc prompting on quality, speed, and reliability.",
        visual: "Workflow blueprint linking input quality, iteration, checks, and final judgment.",
        challenge: "Design your default five-step AI workflow for one recurring task.",
        trap: "Using AI in isolated bursts instead of as part of a designed system.",
      },
      {
        title: "Your role in an AI world",
        scenario: "The highest-value person on the team is not the fastest prompter but the strongest judge of quality, truth, and tradeoffs.",
        visual: "Human advantage map covering judgment, values, taste, accountability, and domain expertise.",
        challenge: "Identify three human strengths you want to become known for in an AI-rich environment.",
        trap: "Assuming tool fluency matters more than judgment.",
      },
      {
        title: "Final synthesis",
        scenario: "A final case blends AI output, weak evidence, and real tradeoffs into one realistic workflow problem that requires both AI literacy and logic.",
        visual: "Operating model showing how all eight modules fit into one decision posture.",
        challenge: "Produce your personal AI operating playbook and stress test it on one realistic case.",
        trap: "Treating the course as information instead of a way of operating.",
      },
    ],
  },
];

export const logicModuleSeeds: FoundationModuleSeed[] = [
  {
    id: "lr-m1",
    title: "Module 1 - What Reasoning Is",
    purpose: "Give learners the grammar of arguments in ordinary language so logic feels practical from day one.",
    outcomes: [
      "Identify claims, premises, and conclusions.",
      "Distinguish assertion from support.",
      "Use fairness before criticism.",
    ],
    signatureInteractions: ["Identify the conclusion", "Argument highlighting"],
    capstone: "Convert a paragraph of persuasive writing into standard argument form.",
    estimatedMinutes: 80,
    lessons: [
      {
        title: "Why reasoning matters",
        scenario: "Two people see the same facts but reach opposite conclusions because their reasoning patterns differ.",
        visual: "Decision chain from assumptions to inferences to outcomes.",
        challenge: "Audit one recent decision and identify where reasoning quality mattered.",
        trap: "Treating reasoning as academic instead of practical.",
      },
      {
        title: "Claims, premises, and conclusions",
        scenario: "A persuasive post feels strong until its supporting reasons and its conclusion are separated and examined.",
        visual: "Argument anatomy showing a claim, supporting premises, and inferred conclusion.",
        challenge: "Take one opinionated paragraph and label every claim, premise, and conclusion.",
        trap: "Mistaking a strong conclusion for strong support.",
      },
      {
        title: "Inference and support",
        scenario: "Two arguments have similar claims, but one actually gives reasons that move us there and the other simply repeats itself.",
        visual: "Support bridge showing how premises are supposed to connect to a conclusion.",
        challenge: "Explain in one sentence how each reason is meant to support one conclusion.",
        trap: "Ignoring the move between reasons and conclusion.",
      },
      {
        title: "Arguments in ordinary language",
        scenario: "A casual conversation contains real reasoning even though nobody uses formal logic vocabulary.",
        visual: "Everyday argument gallery from meetings, texts, headlines, and family conversations.",
        challenge: "Find three arguments in ordinary life and rewrite them in cleaner form.",
        trap: "Thinking logic only appears in textbook examples.",
      },
      {
        title: "The principle of charity",
        scenario: "A disagreement cools down the moment one person reconstructs the other side fairly before responding.",
        visual: "Weak caricature vs fair reconstruction comparison panel.",
        challenge: "Take an argument you dislike and rewrite it in the strongest fair form you can manage.",
        trap: "Critiquing the weakest version of an opposing view.",
      },
    ],
  },
  {
    id: "lr-m2",
    title: "Module 2 - Thinking Errors and Cognitive Traps",
    purpose: "Show that reasoning problems are not just formal mistakes but deeply human mistakes tied to identity, emotion, and cognitive shortcuts.",
    outcomes: [
      "Recognize cognitive traps in yourself and others.",
      "Explain why smart people still reason badly.",
      "Practice humility without becoming indecisive.",
    ],
    signatureInteractions: ["Belief audit", "Bias self-diagnosis", "Would this change your mind?"],
    capstone: "Analyze one personal belief and state what evidence would genuinely change your mind.",
    estimatedMinutes: 80,
    lessons: [
      {
        title: "Why smart people reason badly",
        scenario: "A highly capable person defends a weak conclusion because identity and pressure matter more than raw intelligence.",
        visual: "Reasoning under pressure model linking emotion, identity, incentives, and cognitive load.",
        challenge: "Write down one context where being smart does not protect you from reasoning badly.",
        trap: "Assuming intelligence automatically produces good judgment.",
      },
      {
        title: "Confirmation bias",
        scenario: "A person notices every article that supports their view and forgets the ones that challenge it.",
        visual: "Attention funnel showing how we admit friendly evidence and filter out threatening evidence.",
        challenge: "Do a one-topic evidence audit where you must collect the strongest case against your own view.",
        trap: "Thinking confirmation bias only affects other people.",
      },
      {
        title: "Motivated reasoning",
        scenario: "A conclusion feels right first, and only then does the person go looking for reasons to justify it.",
        visual: "Desire-to-belief loop showing how preferences shape what counts as convincing.",
        challenge: "List one belief where identity, status, or comfort might be shaping your reasoning.",
        trap: "Mistaking a desired conclusion for a well-earned one.",
      },
      {
        title: "Heuristics and shortcuts",
        scenario: "A quick rule of thumb helps under time pressure, but it also pushes the thinker into a costly mistake.",
        visual: "Fast-vs-slow reasoning board showing when shortcuts help and when they mislead.",
        challenge: "Identify one shortcut you use often and name the condition under which it becomes risky.",
        trap: "Treating all quick judgments as irrational or all of them as good enough.",
      },
      {
        title: "Intellectual humility",
        scenario: "A person becomes far more persuasive once they can say what they do not know and what would update their view.",
        visual: "Confidence calibration dial from overconfidence to paralysis to measured uncertainty.",
        challenge: "Rewrite one strong claim you have made recently with a more honest confidence level and update rule.",
        trap: "Thinking humility means weakness or vagueness.",
      },
    ],
  },
  {
    id: "lr-m3",
    title: "Module 3 - Understanding Arguments Properly",
    purpose: "Strengthen analysis before evaluation so learners stop attacking messy impressions and start working with structure.",
    outcomes: [
      "Standardize arguments more clearly.",
      "Find hidden assumptions.",
      "Separate explanation from argument.",
    ],
    signatureInteractions: ["Argument map builder", "Missing-premise challenge"],
    capstone: "Repair one weak argument into its strongest fair version.",
    estimatedMinutes: 75,
    lessons: [
      {
        title: "Standardizing arguments",
        scenario: "A heated conversation becomes much clearer when translated into premise-conclusion form.",
        visual: "Before-and-after panel of messy speech turned into standard argument format.",
        challenge: "Standardize two messy real-world arguments into clean form.",
        trap: "Critiquing arguments before reconstructing them clearly.",
      },
      {
        title: "Hidden premises and assumptions",
        scenario: "An argument seems persuasive until the unstated assumption doing the real work is finally surfaced.",
        visual: "Iceberg model with explicit reasons above the water and hidden assumptions below.",
        challenge: "Find at least two hidden premises in one persuasive article or post.",
        trap: "Ignoring the assumptions that do most of the work.",
      },
      {
        title: "Ambiguity and vagueness",
        scenario: "A proposal sounds reasonable because vague terms hide the lack of precise standards and commitments.",
        visual: "Fog-to-clarity diagram showing how vague language distorts judgment.",
        challenge: "Rewrite one vague claim into a sharper, testable version.",
        trap: "Letting fuzzy language stand in for strong reasoning.",
      },
      {
        title: "Steelmanning vs strawmanning",
        scenario: "A conflict improves as soon as each side stops attacking caricatures and starts engaging the strongest real version.",
        visual: "Side-by-side comparison of strawman, fair summary, and steelman.",
        challenge: "Steelman one opposing argument before evaluating it.",
        trap: "Mistaking easy critique for accurate critique.",
      },
      {
        title: "Explanations vs arguments",
        scenario: "A because-statement gets treated like proof when it is really only describing why something happened.",
        visual: "Split flowchart of explanatory language versus justificatory argument language.",
        challenge: "Label five statements as explanations or arguments and defend each label.",
        trap: "Confusing narrative explanation with justification.",
      },
    ],
  },
  {
    id: "lr-m4",
    title: "Module 4 - Deductive Logic",
    purpose: "Introduce logical rigor in a way that stays practical and usable.",
    outcomes: [
      "Explain validity and soundness.",
      "Recognize common deductive forms.",
      "Spot contradictions and structural failures.",
    ],
    signatureInteractions: ["Valid or invalid drills", "Contradiction detector"],
    capstone: "Test everyday arguments for validity and soundness.",
    estimatedMinutes: 90,
    lessons: [
      {
        title: "What deductive arguments promise",
        scenario: "A compliance decision depends on whether the rule structure guarantees the conclusion if the premises hold.",
        visual: "Necessity chain showing why a conclusion must follow in a deductive argument.",
        challenge: "Find one workplace or policy argument that should be deductive rather than probabilistic.",
        trap: "Thinking deductive logic is only for mathematicians.",
      },
      {
        title: "Validity vs truth",
        scenario: "A formally valid argument reaches a false conclusion because one premise is false even though the structure is strong.",
        visual: "Grid separating structural validity from premise truth.",
        challenge: "Classify three arguments by validity and premise truth separately.",
        trap: "Assuming logical validity means the conclusion is true.",
      },
      {
        title: "Soundness",
        scenario: "A tidy argument collapses because one premise is unsupported even though the structure itself is valid.",
        visual: "Soundness checklist tying valid structure to true or well-supported premises.",
        challenge: "Evaluate one real argument for soundness and identify its weakest premise.",
        trap: "Stopping analysis once the structure looks neat.",
      },
      {
        title: "Common valid and invalid forms",
        scenario: "Two argument patterns sound similar, but one is reliable and the other is a classic trap.",
        visual: "Pattern cards for common valid and invalid forms in everyday language.",
        challenge: "Sort six arguments into valid and invalid forms and explain why.",
        trap: "Relying on surface similarity rather than actual structure.",
      },
      {
        title: "Contradiction, consistency, and logical tension",
        scenario: "A worldview sounds coherent until two of its commitments collide under pressure.",
        visual: "Consistency web highlighting contradiction nodes and unresolved tensions.",
        challenge: "Find and repair one contradiction in a real policy, workflow, or public position.",
        trap: "Treating isolated plausibility as overall consistency.",
      },
      {
        title: "Everyday deductive reasoning",
        scenario: "Rules, contracts, and procedures quietly rely on deductive logic all the time, even when nobody names it.",
        visual: "Rule tree translating conditions into actions and consequences.",
        challenge: "Turn one real-world rule into explicit if-then logic and test edge cases.",
        trap: "Assuming everyday reasoning never uses strict logical form.",
      },
    ],
  },
  {
    id: "lr-m5",
    title: "Module 5 - Inductive Reasoning and Uncertainty",
    purpose: "Teach better judgment in the real world, where certainty is rare and evidence comes in degrees.",
    outcomes: [
      "Assess inductive strength rather than demanding impossible certainty.",
      "Evaluate sample quality and generalization.",
      "Separate causation from correlation more carefully.",
    ],
    signatureInteractions: ["Sample-size game", "Causation diagnostic", "Analogy strength comparison"],
    capstone: "Evaluate real headlines for causal overreach and evidential weakness.",
    estimatedMinutes: 90,
    lessons: [
      {
        title: "What inductive reasoning does",
        scenario: "A forecast guides action even though nobody can know the future with certainty.",
        visual: "Likelihood ladder from weak support to strong support.",
        challenge: "Rewrite one claim so it reflects proper uncertainty instead of fake certainty.",
        trap: "Thinking all good reasoning must produce certainty.",
      },
      {
        title: "Strong vs weak arguments",
        scenario: "Two claims feel equally plausible until you compare the strength, relevance, and sufficiency of their support.",
        visual: "Support-strength rubric covering relevance, sufficiency, and alternative explanations.",
        challenge: "Rank three arguments by inductive strength and explain your ranking.",
        trap: "Letting rhetoric substitute for evidential strength.",
      },
      {
        title: "Generalization and sample quality",
        scenario: "A viral survey gets treated as representative even though the sample is tiny, skewed, or self-selected.",
        visual: "Sample quality dashboard showing size, selection, and representativeness.",
        challenge: "Audit one public claim by asking who was sampled, how, and why it matters.",
        trap: "Generalizing far beyond the evidence base.",
      },
      {
        title: "Causation vs correlation",
        scenario: "A headline turns an association into a causal story and readers barely notice the leap.",
        visual: "Causal funnel from correlation to controls to mechanism to replication.",
        challenge: "Rewrite three causal headlines into more accurate claims.",
        trap: "Treating correlation as if it proves cause.",
      },
      {
        title: "Analogy, prediction, and probability",
        scenario: "A vivid analogy feels persuasive until the missing differences become more important than the shared similarities.",
        visual: "Analogy quality checklist with relevant and irrelevant similarities.",
        challenge: "Create one strong analogy and one misleading analogy for the same claim.",
        trap: "Using surface similarity as if it were structural similarity.",
      },
      {
        title: "Living with uncertainty",
        scenario: "A team delays action waiting for certainty and ends up making a worse decision than if they had reasoned under uncertainty honestly.",
        visual: "Decision board showing reversible and irreversible choices under uncertainty.",
        challenge: "Design a reversible decision plan for one uncertain choice.",
        trap: "Pretending certainty is available when it is not.",
      },
    ],
  },
  {
    id: "lr-m6",
    title: "Module 6 - Fallacies in the Wild",
    purpose: "Make poor reasoning easy to recognize in media, debate, and persuasion without turning learners into shallow label hunters.",
    outcomes: [
      "Spot major informal fallacies in real examples.",
      "Explain why they fail rather than only naming them.",
      "Rewrite stronger alternatives.",
    ],
    signatureInteractions: ["Fallacy cards", "Rewrite challenge", "Media annotation"],
    capstone: "Annotate one persuasive piece for fallacies and stronger rewrites.",
    estimatedMinutes: 90,
    lessons: [
      {
        title: "What a fallacy is and is not",
        scenario: "A legitimate concern gets dismissed with a lazy fallacy accusation instead of real analysis.",
        visual: "Decision tree distinguishing fallacy, weakness, and simple disagreement.",
        challenge: "Review three weak arguments and classify them carefully instead of labeling loosely.",
        trap: "Using fallacy labels as debate weapons rather than diagnostic tools.",
      },
      {
        title: "Relevance fallacies",
        scenario: "A conversation shifts away from the issue and toward emotion, identity, or personality.",
        visual: "Relevance filter showing on-topic reasons and distraction tactics.",
        challenge: "Rewrite one emotionally manipulative argument into a more relevant one.",
        trap: "Following rhetorical heat away from the actual claim.",
      },
      {
        title: "Structural fallacies",
        scenario: "A speaker forces a false choice or predicts a runaway chain of disasters with little support.",
        visual: "Structure failure map showing false dilemma, slippery slope, and circularity.",
        challenge: "Repair one false dilemma by adding the missing alternatives.",
        trap: "Accepting an oversimplified structure because it feels decisive.",
      },
      {
        title: "Evidence fallacies",
        scenario: "Anecdotes, cherry-picked facts, and weak analogies get dressed up as solid support.",
        visual: "Evidence integrity meter from cherry-pick to representative evidence.",
        challenge: "Take one cherry-picked claim and rebuild it using fuller evidence.",
        trap: "Mistaking selected evidence for balanced evidence.",
      },
      {
        title: "Misrepresentation fallacies",
        scenario: "A nuanced claim gets reframed into something easier to attack and the audience never sees the swap.",
        visual: "Distortion spectrum from fair summary to loaded framing to strawman.",
        challenge: "Rewrite one loaded framing example into neutral language.",
        trap: "Attacking a distorted version of the real argument.",
      },
      {
        title: "Fallacy hunting in real media",
        scenario: "Ads, posts, and commentary clips layer multiple fallacies together to drive persuasion.",
        visual: "Media annotation board showing stacked reasoning errors in one piece.",
        challenge: "Annotate a real article, ad, or clip for at least five reasoning weaknesses.",
        trap: "Thinking fallacies only happen in obviously bad arguments.",
      },
    ],
  },
  {
    id: "lr-m7",
    title: "Module 7 - Evidence, Sources, and Credibility",
    purpose: "Turn learners into disciplined evaluators of proof quality, expertise, and trust signals.",
    outcomes: [
      "Rank evidence quality more carefully.",
      "Assess source credibility with explicit criteria.",
      "Detect statistical and media misdirection.",
    ],
    signatureInteractions: ["Source ladder", "Evidence ranking", "Misleading graph challenge"],
    capstone: "Build an evidence profile for one controversial claim using multiple source types.",
    estimatedMinutes: 90,
    lessons: [
      {
        title: "What counts as evidence",
        scenario: "A debate treats anecdotes, expertise, data, and experiments as if they all carried equal weight.",
        visual: "Evidence ladder ranking forms of support by reliability and context.",
        challenge: "Classify and rank the evidence in one argument from strongest to weakest.",
        trap: "Treating all support as equally probative.",
      },
      {
        title: "Source credibility",
        scenario: "A confident personality is mistaken for a qualified expert because delivery gets confused with authority.",
        visual: "Credibility scorecard covering expertise, incentives, transparency, and track record.",
        challenge: "Score three sources and explain why your trust differs across them.",
        trap: "Letting charisma or polish substitute for credibility.",
      },
      {
        title: "Statistics that mislead",
        scenario: "A chart uses real numbers but still misleads through framing, scaling, and omitted context.",
        visual: "Gallery of misleading graphs with corrected versions beside them.",
        challenge: "Repair one misleading graph so it communicates honestly.",
        trap: "Assuming numerical presentation guarantees honesty.",
      },
      {
        title: "Scientific reasoning for non-scientists",
        scenario: "A dramatic scientific claim sounds final until you ask about method, replication, uncertainty, and incentives.",
        visual: "Scientific reasoning cycle from hypothesis to test to replication to update.",
        challenge: "Evaluate one scientific claim using method, evidence, and replication criteria.",
        trap: "Treating one study like settled truth.",
      },
      {
        title: "Media literacy and claim evaluation",
        scenario: "A headline creates a strong impression that the article evidence does not fully support.",
        visual: "Headline-to-evidence parsing frame separating attention hook from actual support.",
        challenge: "Run a claim evaluation worksheet on one viral post or headline.",
        trap: "Letting urgency or outrage outrun evidence review.",
      },
      {
        title: "Evaluating AI output as evidence",
        scenario: "An AI answer sounds authoritative even though it is only another claim that still needs source and logic checks.",
        visual: "AI evidence protocol tying fluency to source, logic, and domain review.",
        challenge: "Take one AI answer and build an evidence profile for it like any other claim.",
        trap: "Treating fluent generated text as evidence by itself.",
      },
    ],
  },
  {
    id: "lr-m8",
    title: "Module 8 - Reasoning in Real Life",
    purpose: "Make logic transferable to relationships, work, media, ethics, and AI-assisted environments.",
    outcomes: [
      "Reason better in conversation and at work.",
      "Handle pressure with more discipline.",
      "Integrate logic into AI-assisted decisions.",
    ],
    signatureInteractions: ["Decision trees", "Argument clinic", "Final reasoning audit"],
    capstone: "Rank claims from news, work, and AI outputs by reasoning and evidence strength.",
    estimatedMinutes: 90,
    lessons: [
      {
        title: "Reasoning in relationships and conversation",
        scenario: "A tense disagreement improves when one person starts listening for claims and assumptions instead of rehearsing rebuttals.",
        visual: "Conversation loop showing listen, clarify, reconstruct, evaluate, and respond.",
        challenge: "Use a charity-first method in one real conversation this week.",
        trap: "Trying to win before you understand.",
      },
      {
        title: "Reasoning at work",
        scenario: "A proposal becomes much stronger once assumptions, evidence, tradeoffs, and risks are made explicit.",
        visual: "Decision memo template showing claim, evidence, tradeoff, uncertainty, and risk.",
        challenge: "Refactor one proposal using explicit reasoning sections.",
        trap: "Hiding weak reasoning behind presentation polish.",
      },
      {
        title: "Reasoning about moral and political claims",
        scenario: "A heated issue becomes clearer once value claims, factual claims, and tradeoffs are separated.",
        visual: "Matrix separating values, evidence, uncertainty, and tradeoffs.",
        challenge: "Analyze one public issue by separating empirical questions from value questions.",
        trap: "Treating every disagreement as purely factual or purely moral.",
      },
      {
        title: "Reasoning under pressure",
        scenario: "Stress, urgency, and identity threat shrink reasoning quality unless guardrails are prepared in advance.",
        visual: "Pressure-proofing checklist for urgent decisions.",
        challenge: "Create a rapid-decision checklist for one high-pressure context.",
        trap: "Believing pressure excuses bad process.",
      },
      {
        title: "Logic and AI together",
        scenario: "A human catches an AI mistake only because they know how to test claims, assumptions, evidence, and causal leaps.",
        visual: "Human-AI reasoning loop linking prompt, answer, critique, verification, and decision.",
        challenge: "Run one AI-generated answer through a full reasoning audit.",
        trap: "Using AI without bringing logic to the interaction.",
      },
      {
        title: "Final synthesis",
        scenario: "A realistic bundle of claims from work, media, and AI demands disciplined judgment across the whole course.",
        visual: "Reasoner operating system diagram connecting habits from all eight modules.",
        challenge: "Write your personal reasoning charter and test it against one live issue.",
        trap: "Treating logic as knowledge instead of a repeatable habit.",
      },
    ],
  },
];
