import mysql from "mysql2/promise";
import * as dotenv from "dotenv";
dotenv.config();

const DB_URL = process.env.DATABASE_URL;
if (!DB_URL) { console.error("DATABASE_URL not set"); process.exit(1); }

const conn = await mysql.createConnection(DB_URL);

const resources = [
  // ── AI & Machine Learning ──────────────────────────────────────────────────
  {
    title: "Attention Is All You Need",
    description: "The original Transformer paper that revolutionized NLP and modern AI. Essential reading for understanding how LLMs work.",
    url: "https://arxiv.org/abs/1706.03762",
    category: "AI & Machine Learning",
    tags: JSON.stringify(["transformers", "attention", "NLP", "deep learning", "foundational"]),
    type: "paper",
    difficulty: "advanced",
    featured: 1,
    author: "Vaswani et al.",
    estimatedMinutes: 45,
  },
  {
    title: "fast.ai Practical Deep Learning",
    description: "The best free course for learning deep learning from a top-down, practical perspective. Used by thousands of practitioners.",
    url: "https://course.fast.ai",
    category: "AI & Machine Learning",
    tags: JSON.stringify(["deep learning", "PyTorch", "practical", "free course"]),
    type: "course",
    difficulty: "intermediate",
    featured: 1,
    author: "Jeremy Howard",
    estimatedMinutes: 2400,
  },
  {
    title: "Andrej Karpathy: Neural Networks Zero to Hero",
    description: "Build neural networks from scratch in Python. Karpathy's legendary YouTube series — the clearest explanation of backprop ever made.",
    url: "https://karpathy.ai/zero-to-hero.html",
    category: "AI & Machine Learning",
    tags: JSON.stringify(["neural networks", "backpropagation", "Python", "GPT", "from scratch"]),
    type: "course",
    difficulty: "intermediate",
    featured: 1,
    author: "Andrej Karpathy",
    estimatedMinutes: 1200,
  },
  {
    title: "The Illustrated Transformer",
    description: "Jay Alammar's visual, intuitive explanation of the Transformer architecture. The best visual guide to how attention works.",
    url: "https://jalammar.github.io/illustrated-transformer/",
    category: "AI & Machine Learning",
    tags: JSON.stringify(["transformers", "visualization", "attention", "explainer"]),
    type: "article",
    difficulty: "intermediate",
    featured: 0,
    author: "Jay Alammar",
    estimatedMinutes: 30,
  },
  {
    title: "Hugging Face NLP Course",
    description: "Free, comprehensive course on using Transformers and the Hugging Face ecosystem for NLP tasks.",
    url: "https://huggingface.co/learn/nlp-course",
    category: "AI & Machine Learning",
    tags: JSON.stringify(["NLP", "transformers", "Hugging Face", "BERT", "fine-tuning"]),
    type: "course",
    difficulty: "intermediate",
    featured: 0,
    author: "Hugging Face",
    estimatedMinutes: 1800,
  },
  {
    title: "Stanford CS229: Machine Learning",
    description: "Andrew Ng's legendary Stanford ML course. Rigorous mathematical foundations of supervised, unsupervised, and reinforcement learning.",
    url: "https://cs229.stanford.edu/",
    category: "AI & Machine Learning",
    tags: JSON.stringify(["machine learning", "Stanford", "Andrew Ng", "mathematics", "foundations"]),
    type: "course",
    difficulty: "advanced",
    featured: 0,
    author: "Andrew Ng",
    estimatedMinutes: 3000,
  },
  {
    title: "Prompt Engineering Guide",
    description: "Comprehensive, community-maintained guide to prompt engineering techniques for LLMs — chain-of-thought, few-shot, RAG, and more.",
    url: "https://www.promptingguide.ai/",
    category: "AI & Machine Learning",
    tags: JSON.stringify(["prompt engineering", "LLM", "chain-of-thought", "few-shot", "RAG"]),
    type: "article",
    difficulty: "beginner",
    featured: 1,
    author: "DAIR.AI",
    estimatedMinutes: 120,
  },

  // ── Web Development ────────────────────────────────────────────────────────
  {
    title: "The Odin Project",
    description: "Free, open-source full-stack web development curriculum. One of the most comprehensive and respected free paths to becoming a developer.",
    url: "https://www.theodinproject.com/",
    category: "Web Development",
    tags: JSON.stringify(["HTML", "CSS", "JavaScript", "React", "Node.js", "full-stack", "free"]),
    type: "course",
    difficulty: "beginner",
    featured: 1,
    author: "The Odin Project",
    estimatedMinutes: 6000,
  },
  {
    title: "Josh Comeau's CSS for JavaScript Developers",
    description: "The definitive modern CSS course. Covers flexbox, grid, animations, and the mental models that make CSS finally make sense.",
    url: "https://css-for-js.dev/",
    category: "Web Development",
    tags: JSON.stringify(["CSS", "flexbox", "grid", "animations", "JavaScript"]),
    type: "course",
    difficulty: "intermediate",
    featured: 0,
    author: "Josh Comeau",
    estimatedMinutes: 1500,
  },
  {
    title: "React Official Docs (New)",
    description: "The completely rewritten React documentation with interactive examples, hooks deep-dives, and the new mental model for React 18+.",
    url: "https://react.dev/",
    category: "Web Development",
    tags: JSON.stringify(["React", "hooks", "components", "state", "official docs"]),
    type: "article",
    difficulty: "beginner",
    featured: 1,
    author: "Meta",
    estimatedMinutes: 300,
  },
  {
    title: "web.dev by Google",
    description: "Google's authoritative resource for modern web development best practices — performance, accessibility, PWAs, and Core Web Vitals.",
    url: "https://web.dev/",
    category: "Web Development",
    tags: JSON.stringify(["performance", "accessibility", "PWA", "Core Web Vitals", "Google"]),
    type: "article",
    difficulty: "intermediate",
    featured: 0,
    author: "Google",
    estimatedMinutes: 240,
  },
  {
    title: "TypeScript Deep Dive",
    description: "The most thorough free TypeScript book available. Covers the type system in depth with practical examples.",
    url: "https://basarat.gitbook.io/typescript/",
    category: "Web Development",
    tags: JSON.stringify(["TypeScript", "type system", "generics", "advanced types"]),
    type: "book",
    difficulty: "intermediate",
    featured: 0,
    author: "Basarat Ali Syed",
    estimatedMinutes: 600,
  },

  // ── Data Science ───────────────────────────────────────────────────────────
  {
    title: "Kaggle Learn",
    description: "Free, hands-on micro-courses in Python, pandas, SQL, ML, and data visualization. Each course takes 2-4 hours with interactive notebooks.",
    url: "https://www.kaggle.com/learn",
    category: "Data Science",
    tags: JSON.stringify(["Python", "pandas", "SQL", "machine learning", "data visualization", "free"]),
    type: "course",
    difficulty: "beginner",
    featured: 1,
    author: "Kaggle",
    estimatedMinutes: 800,
  },
  {
    title: "Statistics and Probability — Khan Academy",
    description: "Comprehensive statistics curriculum covering probability, distributions, hypothesis testing, and regression. Free and interactive.",
    url: "https://www.khanacademy.org/math/statistics-probability",
    category: "Data Science",
    tags: JSON.stringify(["statistics", "probability", "hypothesis testing", "regression", "Khan Academy"]),
    type: "course",
    difficulty: "beginner",
    featured: 0,
    author: "Khan Academy",
    estimatedMinutes: 1200,
  },
  {
    title: "Seeing Theory: Visual Introduction to Probability",
    description: "Stunning interactive visualizations of probability and statistics concepts. Makes abstract math tangible and intuitive.",
    url: "https://seeing-theory.brown.edu/",
    category: "Data Science",
    tags: JSON.stringify(["probability", "statistics", "visualization", "interactive", "intuition"]),
    type: "tool",
    difficulty: "beginner",
    featured: 1,
    author: "Brown University",
    estimatedMinutes: 60,
  },
  {
    title: "Python Data Science Handbook",
    description: "Jake VanderPlas's comprehensive guide to NumPy, pandas, Matplotlib, and scikit-learn. Free to read online.",
    url: "https://jakevdp.github.io/PythonDataScienceHandbook/",
    category: "Data Science",
    tags: JSON.stringify(["Python", "NumPy", "pandas", "scikit-learn", "Matplotlib", "free book"]),
    type: "book",
    difficulty: "intermediate",
    featured: 0,
    author: "Jake VanderPlas",
    estimatedMinutes: 900,
  },

  // ── Computer Science Fundamentals ──────────────────────────────────────────
  {
    title: "CS50x: Introduction to Computer Science",
    description: "Harvard's legendary intro CS course. The most-watched computer science course in the world. Covers C, Python, SQL, HTML, and more.",
    url: "https://cs50.harvard.edu/x/",
    category: "Computer Science",
    tags: JSON.stringify(["CS fundamentals", "Harvard", "C", "Python", "algorithms", "free"]),
    type: "course",
    difficulty: "beginner",
    featured: 1,
    author: "David Malan",
    estimatedMinutes: 3000,
  },
  {
    title: "Algorithms, Part I — Princeton (Coursera)",
    description: "Robert Sedgewick's rigorous algorithms course. Covers sorting, searching, graphs, and data structures with Java implementations.",
    url: "https://www.coursera.org/learn/algorithms-part1",
    category: "Computer Science",
    tags: JSON.stringify(["algorithms", "data structures", "sorting", "graphs", "Princeton"]),
    type: "course",
    difficulty: "intermediate",
    featured: 0,
    author: "Robert Sedgewick",
    estimatedMinutes: 2400,
  },
  {
    title: "Nand to Tetris",
    description: "Build a modern computer from first principles — from logic gates to a working operating system. One of the most profound CS experiences available.",
    url: "https://www.nand2tetris.org/",
    category: "Computer Science",
    tags: JSON.stringify(["computer architecture", "hardware", "operating systems", "from scratch", "foundational"]),
    type: "course",
    difficulty: "intermediate",
    featured: 1,
    author: "Noam Nisan & Shimon Schocken",
    estimatedMinutes: 2400,
  },
  {
    title: "Visualgo: Algorithm Visualizations",
    description: "Interactive visualizations of data structures and algorithms. Watch sorting, graph traversal, and tree operations in real-time.",
    url: "https://visualgo.net/",
    category: "Computer Science",
    tags: JSON.stringify(["algorithms", "visualization", "interactive", "sorting", "graphs", "trees"]),
    type: "tool",
    difficulty: "beginner",
    featured: 0,
    author: "Steven Halim",
    estimatedMinutes: 60,
  },

  // ── Productivity & Learning Science ───────────────────────────────────────
  {
    title: "Make It Stick: The Science of Successful Learning",
    description: "Evidence-based book on how memory and learning actually work — spaced repetition, retrieval practice, interleaving. Transforms how you study.",
    url: "https://www.amazon.com/Make-Stick-Science-Successful-Learning/dp/0674729013",
    category: "Learning Science",
    tags: JSON.stringify(["spaced repetition", "retrieval practice", "memory", "learning science", "book"]),
    type: "book",
    difficulty: "beginner",
    featured: 1,
    author: "Brown, Roediger & McDaniel",
    estimatedMinutes: 300,
  },
  {
    title: "Gwern: Spaced Repetition for Efficient Learning",
    description: "The definitive deep-dive on spaced repetition — the science, the algorithms (SM-2, FSRS), and practical implementation advice.",
    url: "https://gwern.net/spaced-repetition",
    category: "Learning Science",
    tags: JSON.stringify(["spaced repetition", "SM-2", "Anki", "memory", "learning science"]),
    type: "article",
    difficulty: "intermediate",
    featured: 0,
    author: "Gwern Branwen",
    estimatedMinutes: 60,
  },
  {
    title: "Learning How to Learn (Coursera)",
    description: "Barbara Oakley's course on the neuroscience of learning. Covers focused vs. diffuse thinking, procrastination, and memory techniques.",
    url: "https://www.coursera.org/learn/learning-how-to-learn",
    category: "Learning Science",
    tags: JSON.stringify(["neuroscience", "learning techniques", "memory", "procrastination", "free"]),
    type: "course",
    difficulty: "beginner",
    featured: 1,
    author: "Barbara Oakley",
    estimatedMinutes: 480,
  },
  {
    title: "Zettelkasten Method",
    description: "Niklas Luhmann's legendary note-taking system that produced 70+ books. The most powerful personal knowledge management method ever devised.",
    url: "https://zettelkasten.de/introduction/",
    category: "Learning Science",
    tags: JSON.stringify(["note-taking", "PKM", "Zettelkasten", "knowledge management", "writing"]),
    type: "article",
    difficulty: "beginner",
    featured: 0,
    author: "Zettelkasten.de",
    estimatedMinutes: 30,
  },

  // ── Mathematics ────────────────────────────────────────────────────────────
  {
    title: "3Blue1Brown: Essence of Linear Algebra",
    description: "Grant Sanderson's visual series on linear algebra. Builds geometric intuition for vectors, matrices, and transformations. Essential for AI/ML.",
    url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab",
    category: "Mathematics",
    tags: JSON.stringify(["linear algebra", "vectors", "matrices", "visualization", "intuition", "AI/ML"]),
    type: "course",
    difficulty: "beginner",
    featured: 1,
    author: "3Blue1Brown",
    estimatedMinutes: 240,
  },
  {
    title: "Mathematics for Machine Learning",
    description: "Free textbook covering the mathematical foundations of ML: linear algebra, calculus, probability, and statistics. Available free online.",
    url: "https://mml-book.github.io/",
    category: "Mathematics",
    tags: JSON.stringify(["linear algebra", "calculus", "probability", "statistics", "machine learning", "free book"]),
    type: "book",
    difficulty: "advanced",
    featured: 0,
    author: "Deisenroth, Faisal & Ong",
    estimatedMinutes: 1200,
  },
  {
    title: "Paul's Online Math Notes",
    description: "Comprehensive free notes for Calculus I-III, Differential Equations, and Linear Algebra. The best reference for college-level math.",
    url: "https://tutorial.math.lamar.edu/",
    category: "Mathematics",
    tags: JSON.stringify(["calculus", "differential equations", "linear algebra", "reference", "free"]),
    type: "article",
    difficulty: "intermediate",
    featured: 0,
    author: "Paul Dawkins",
    estimatedMinutes: 600,
  },

  // ── Tools & Productivity ───────────────────────────────────────────────────
  {
    title: "Obsidian",
    description: "The most powerful local-first knowledge management tool. Markdown-based, with a graph view, plugins, and a thriving community.",
    url: "https://obsidian.md/",
    category: "Tools",
    tags: JSON.stringify(["note-taking", "PKM", "Markdown", "knowledge graph", "Zettelkasten"]),
    type: "tool",
    difficulty: "beginner",
    featured: 1,
    author: "Obsidian",
    estimatedMinutes: 30,
  },
  {
    title: "Anki",
    description: "The gold standard spaced repetition flashcard app. Used by medical students, language learners, and anyone serious about long-term retention.",
    url: "https://apps.ankiweb.net/",
    category: "Tools",
    tags: JSON.stringify(["spaced repetition", "flashcards", "memory", "SM-2", "free"]),
    type: "tool",
    difficulty: "beginner",
    featured: 0,
    author: "Damien Elmes",
    estimatedMinutes: 20,
  },
  {
    title: "Excalidraw",
    description: "Free, open-source virtual whiteboard for sketching diagrams, mind maps, and visual thinking. Collaborative and beautifully simple.",
    url: "https://excalidraw.com/",
    category: "Tools",
    tags: JSON.stringify(["whiteboard", "diagrams", "mind maps", "visual thinking", "free", "collaborative"]),
    type: "tool",
    difficulty: "beginner",
    featured: 0,
    author: "Excalidraw",
    estimatedMinutes: 10,
  },
];

try {
  await conn.execute("DELETE FROM library_resources WHERE 1=1");
  console.log("Cleared existing library resources.");

  for (const r of resources) {
    await conn.execute(
      `INSERT INTO library_resources (title, description, url, category, tags, type, difficulty, featured)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
      [r.title, r.description, r.url, r.category, r.tags, r.type, r.difficulty, r.featured]
    );
  }

  console.log(`✅ Seeded ${resources.length} library resources across ${[...new Set(resources.map(r => r.category))].length} categories.`);
} catch (err) {
  console.error("Seed error:", err);
} finally {
  await conn.end();
}
