/**
 * Vocabulary map — every key term in the AI Literacy course with three
 * reading-level variants. The seed factory selects a variant based on the
 * learner's profile.readingLevel.
 *
 * Glosses are multi-paragraph lesson content (separated by \n\n), not just
 * dictionary definitions. Each should stand alone as a readable mini-lesson.
 */

import type { ReadingLevel } from "../../types/learnerProfile";

export interface VocabEntry {
  term: string;
  glosses: Record<ReadingLevel, string>;
  /** Optional analogy used by the analogy block for visual learners. */
  analogy?: string;
}

export const VOCABULARY: Record<string, VocabEntry> = {
  "artificial-intelligence": {
    term: "Artificial Intelligence",
    glosses: {
      plain:
        "Artificial Intelligence — AI — means getting computers to do things that normally need a person. Things like understanding what you say, recognising faces, suggesting what to watch next, or flagging a suspicious bank transaction.\n\nHere's the most important thing to know: today's AI is really good at one specific job, and almost useless at everything else. The AI that recommends shows on Netflix can't help you write an email. The one that flags fraud at your bank can't recognise your face. Every AI is narrow — built for one thing.\n\nAI is not magic. It does not think. It does not feel. It is a very powerful tool that learned patterns from huge amounts of data — and it will repeat those patterns, including the bad ones.",
      standard:
        "Artificial Intelligence refers to software systems designed to perform tasks that have historically required human intelligence — things like recognising what's in a photo, translating between languages, spotting patterns in financial data, or generating natural-sounding text.\n\nUnlike traditional software, which follows rules a programmer explicitly writes ('if temperature is below 32°F, show snow warning'), AI systems learn their own rules by processing enormous amounts of example data. Show a model millions of labelled medical images and it will discover which visual patterns signal disease — no programmer needs to define those patterns in advance.\n\nThe crucial thing to hold onto: today's AI is extremely powerful within narrow boundaries, and extremely brittle outside them. The image recogniser has no idea how to write code. The code assistant cannot diagnose a medical scan. Every AI system in production today is 'narrow AI' — designed for a specific task, optimised for that task, and unreliable the moment it's pushed beyond that boundary.\n\nAI is not magic, and it is not a replacement for human judgment. It is a powerful pattern-recognition tool that does exactly what its training prepared it to do — no more, no less.",
      technical:
        "Artificial Intelligence is an umbrella term for computational systems that approximate cognitive functions through learned representations rather than hand-authored rules. The dominant paradigm since ~2012 has been deep learning: gradient-descent optimisation of neural network parameters over large supervised, self-supervised, or reinforcement-learning objectives.\n\nModern AI systems are fundamentally statistical engines. A language model assigns probability distributions over token sequences; a vision model assigns probability distributions over class labels. Neither system 'understands' in any phenomenological sense — both are performing high-dimensional interpolation over their training distribution.\n\nThe key architectural constraint is the training distribution boundary. Current models generalise well within-distribution and degrade unpredictably out-of-distribution. This is why all deployed AI is narrow AI: capability is tightly coupled to the statistical structure of the training corpus and objective function. Capability outside that structure is not robustly generalisable.\n\nPractical implication: every AI deployment decision should be preceded by asking (1) does the deployment distribution match the training distribution, (2) how are out-of-distribution inputs handled, and (3) what is the consequence of a confident wrong answer?",
    },
  },

  "narrow-ai": {
    term: "Narrow AI",
    glosses: {
      plain:
        "'Narrow AI' means an AI that is great at one specific job — and only that job. The spam filter in your email is brilliant at sorting spam. But it has no idea how to answer a question. The voice assistant on your phone can understand speech — but it doesn't know how to spot a tumour on an X-ray. Every AI you have ever used is narrow AI.\n\nPeople sometimes talk about 'AGI' — Artificial General Intelligence — which would be an AI that can do anything a human can. That doesn't exist yet. All the impressive things you've seen AI do (winning chess, writing essays, generating images) are narrow tasks that took years of work by huge teams on massive amounts of data. They look impressive because they're things humans find hard. But they are still narrow.\n\nWhy does this matter? Because narrow AI fails silently outside its training. It doesn't say 'I don't know.' It gives you an answer that sounds confident — and is often wrong.",
      standard:
        "Every AI system in production today is narrow AI: it excels at the specific task it was trained on, and performance degrades sharply outside that scope. The recommendation algorithm that knows your streaming taste cannot draft an email. The fraud detection model that flags suspicious transactions cannot recognise a face. Capability in one domain does not transfer to another.\n\nThis stands in contrast to Artificial General Intelligence (AGI) — a hypothetical system that could match human cognitive flexibility across arbitrary tasks. AGI does not exist. Every headline you have ever read about AI 'surpassing human intelligence' refers to a narrow benchmark: a specific task, a specific dataset, a specific set of rules.\n\nThe practical risk of narrow AI is overconfidence at distribution boundaries. A model deployed in a new context — different population, different language, different usage pattern — does not know it's out of its depth. It continues producing outputs that look authoritative. This is why context-matching (ensuring the deployment situation resembles the training situation) is one of the most important checks before deploying AI in a new setting.",
      technical:
        "Narrow AI describes task-specific systems lacking domain transfer — the dominant paradigm in all currently deployed AI. These systems are optimised over a fixed distribution P(X,Y) and their generalisation guarantees are theoretically bounded to that distribution.\n\nContrast with Artificial General Intelligence (AGI), a hypothetical system capable of open-ended learning and cross-domain transfer, equivalent in scope to human cognition. No current architecture meets this criterion. Claims of 'superhuman AI' invariably refer to performance on specific benchmarks (ImageNet top-1 accuracy, Go, specific reasoning tasks) not open-domain general capability.\n\nThe key failure mode of narrow AI at deployment boundaries is distribution shift: when P_deploy(X) ≠ P_train(X), model confidence remains high while accuracy drops. Models do not have uncertainty representations adequate to flag this condition reliably. This motivates out-of-distribution detection, calibration research, and the operational practice of monitoring prediction confidence distributions over time after deployment.",
    },
  },

  "machine-learning": {
    term: "Machine Learning",
    glosses: {
      plain:
        "Machine learning is how you teach a computer without writing exact rules. Instead of telling a spam filter 'if the email says FREE MONEY delete it,' you show it a million examples of spam and a million examples of normal email. The computer figures out the patterns itself.\n\nThink of it like training a dog. You don't explain the concept of 'sit' in dog language — you reward the right behaviour until the pattern sticks. Machine learning works the same way, just with numbers and millions of examples instead of treats.\n\nThe catch: whatever patterns were in your training examples are now baked into your model. If your spam examples were mostly in English, the filter may miss spam in other languages. If your examples had hidden biases, the model learned those too. The model learns from data — and data reflects the world as it was, not as it should be.",
      standard:
        "Machine learning is a subfield of AI in which systems discover patterns and improve at a task by processing examples, rather than following hand-written rules. A developer doesn't define what makes a photo a cat — they feed the model millions of labelled images and let it discover the distinguishing features through optimisation.\n\nThere are three main paradigms. Supervised learning trains on labelled input-output pairs (email → spam/not spam). Unsupervised learning finds structure in unlabelled data (customer segmentation). Reinforcement learning optimises behaviour through reward signals (game-playing agents). Most AI products you use daily are built on supervised or self-supervised variants.\n\nThe central implication: machine learning models are mirrors of their training data. They amplify the patterns that were present — including historical biases, gaps in representation, and errors in labelling. A model trained on biased hiring data will produce biased hiring predictions. This is not a bug in the model; it is an accurate reflection of the biased data. Correcting it requires intentional intervention, not just more data.",
      technical:
        "Machine learning is the discipline of constructing models that generalise from training data by minimising a loss function over a parameterised hypothesis space. The model h_θ is selected via empirical risk minimisation: θ* = argmin E[(h_θ(X), Y)] over the training distribution.\n\nThree primary paradigms: supervised learning (labelled pairs (x,y) from a joint distribution P(X,Y)); unsupervised learning (structure discovery over P(X) without labels); reinforcement learning (policy optimisation via reward signal from environment interaction). Contemporary LLMs use self-supervised objectives (next-token prediction, masked token prediction) that scale with corpus size and model parameters.\n\nGeneralisation is the central theoretical concern. Uniform convergence results (PAC learning, VC dimension) bound generalisation error under IID assumptions. In practice, neural network generalisation exceeds classical bounds (the 'generalisation puzzle'), attributed to implicit regularisation from SGD dynamics and architectural inductive biases. Key failure case: distribution shift invalidates IID assumptions and generalisation guarantees simultaneously.",
    },
  },

  "neural-network": {
    term: "Neural Network",
    glosses: {
      plain:
        "A neural network is the type of computer program behind most modern AI — language models, image recognition, voice assistants. The name comes from a loose resemblance to the brain: it's made up of layers of simple calculation units (called neurons) that pass information to each other.\n\nHere's the important thing: it's not actually like a brain. Real neurons are biological cells; artificial neurons are just math. The 'learning' is billions of tiny numbers being adjusted until the model's outputs match the training examples closely enough.\n\nWhat made neural networks go from a niche idea to the technology powering trillion-dollar companies? Two things: enormous datasets and enormous computing power. The models you hear about — GPT, Claude, Gemini — have hundreds of billions of those adjustable numbers. Training them costs tens of millions of dollars and produces a system that is genuinely useful — but in ways its creators cannot fully explain.",
      standard:
        "Neural networks are the dominant architecture behind modern AI — large language models, image classifiers, voice recognition, recommendation systems. They are loosely inspired by the biological brain but function quite differently: each 'neuron' is simply a mathematical function that takes in numbers, applies a weighted sum, and passes the result to the next layer.\n\nThe learning process involves adjusting billions of internal weight values to minimise the difference between the model's predictions and the correct answers in the training data. This is done through an algorithm called backpropagation, which propagates error signals backward through the layers and nudges each weight slightly toward better predictions.\n\nThe word 'deep' in 'deep learning' just means the network has many layers — sometimes hundreds. More layers allow the network to learn progressively more abstract representations: an image model's early layers detect edges; middle layers detect shapes; later layers detect objects. This is why these models can do things that rule-based systems could not: they discover their own representations from data rather than relying on features a human engineered.\n\nA key limitation: neural networks are largely uninterpretable. We can see what they predict; we usually cannot trace exactly why.",
      technical:
        "Neural networks are parameterised function approximators composed of affine transformations and element-wise non-linearities, organised in a directed acyclic computation graph. A feedforward network computes f(x) = σ_L(W_L · σ_{L-1}(W_{L-1} · ... σ_1(W_1 x + b_1)...)) where σ_i are activation functions and W_i, b_i are learned parameters.\n\nTraining proceeds via stochastic gradient descent on a loss function L(f(x), y), with gradients computed via reverse-mode automatic differentiation (backpropagation). Modern training involves: batch normalisation for training stability, residual connections to mitigate vanishing gradients in deep networks, dropout for regularisation, and Adam or AdamW optimisers for adaptive learning rates.\n\nThe transformer architecture (Vaswani et al., 2017) dominates language and multi-modal modelling. Its core mechanism — scaled dot-product attention — computes contextualised representations over arbitrary-length input sequences in O(n²) time. Architectural variants (sparse attention, linear attention, state-space models) trade approximation quality for computational efficiency.\n\nInterpretability remains an open problem. Feature attribution methods (integrated gradients, SHAP), probing classifiers, and mechanistic interpretability (circuit-level analysis of learned algorithms) provide partial insight. No method yet delivers full causal explanation of model behaviour.",
    },
    analogy:
      "Think of it like a committee of specialists: one member notices straight lines, another spots curves, a third recognises noses, a fourth identifies faces. Each member hands their observation to the next. The network 'learns' which features matter by adjusting how much weight each member's opinion carries — and does this adjustment billions of times over millions of examples.",
  },

  "training-data": {
    term: "Training Data",
    glosses: {
      plain:
        "Training data is the collection of examples a model learns from. Want to build a spam filter? You need thousands of examples of spam and non-spam. Want to build an image recogniser? You need millions of labelled photos. The training data is where all the model's knowledge comes from.\n\nThis creates a 'garbage in, garbage out' problem. If your training data is biased, incomplete, or full of errors, the model learns those flaws. A medical AI trained mostly on data from one country may work poorly in another. A language model trained on text from the internet inherits the prejudices in that text.\n\nTraining data is also why AI knowledge goes stale. Most models are trained once and then frozen. They don't update themselves. Ask an LLM about an event from last week and it might not know — or worse, it might invent a plausible-sounding answer based on older patterns. Always check when a model's training data was cut off.",
      standard:
        "Training data is the collection of examples used to teach a machine learning model — it is the sole source of everything the model knows. A language model trained on text learns patterns of language from that text. An image classifier trained on labelled photos learns to map visual features to class labels. No knowledge, value, or bias can enter the model through any other path.\n\nThis creates several important implications for users. First, data quality determines model quality. Mislabelled examples, gaps in demographic representation, and historical patterns of human bias all get encoded into model parameters. The model does not discriminate between facts and prejudices — it learns whatever patterns are present. Second, data scope determines knowledge scope. A model with a training data cutoff of a certain date has no knowledge of events after that date — and, critically, may confabulate plausible-sounding answers when asked about events it does not know. Third, data is not neutral. Every curation decision — what to include, how to label it, whose annotation is trusted — encodes someone's values. 'The data says so' is never an escape from normative choice.\n\nUnderstanding training data helps you ask better questions of AI products: What was it trained on? When was the cutoff? What populations are and are not represented?",
      technical:
        "Training data is the empirical distribution that defines a model's knowledge, capabilities, and failure modes. The model learns a function f: X → Y by minimising expected loss over {(xᵢ, yᵢ)} drawn from P_train(X,Y). Generalisation performance is bounded by how well P_train approximates P_deploy.\n\nData quality dimensions: (1) Label accuracy — annotation noise degrades generalisation, particularly in low-resource settings. (2) Distributional coverage — underrepresented subgroups produce higher prediction error on those subgroups, yielding disparate impact. (3) Temporal coverage — training cutoffs create knowledge boundaries; models deploy on P_deploy which shifts over time relative to P_train. (4) Annotation schema — label design encodes normative choices that propagate into model behaviour.\n\nFor large language models, training corpora consist of internet-scale text, books, and code — an estimated 10^12–10^13 tokens. Curation involves deduplication, quality filtering, and toxicity reduction. These curation decisions are under-documented and create poorly characterised distributional properties. Bias inheritance from training corpora is not fully addressable post-hoc; interventions like RLHF and constitutional AI provide partial mitigation by shaping the preference distribution over the model's output distribution.",
    },
  },

  agi: {
    term: "Artificial General Intelligence (AGI)",
    glosses: {
      plain:
        "AGI — Artificial General Intelligence — is the AI that science fiction imagines: a machine that can think about anything, learn any skill, and apply knowledge flexibly the way a human does. The robot that can be a doctor, a lawyer, a musician, and a friend. That doesn't exist yet.\n\nEvery AI system you have used is 'narrow AI' — amazing at one thing, useless at most others. AlphaGo mastered Go, one of the hardest board games ever invented. It cannot play chess without being retrained. ChatGPT can hold a remarkably human-seeming conversation. It cannot reliably count to ten if you give it a novel arithmetic problem.\n\nWhen you see headlines saying 'AI is now smarter than humans,' they mean on one specific test, for one specific task. They do not mean the AI has become generally intelligent. AGI, if it ever arrives, would be a genuinely transformative moment in history — but it would look very different from the tools available today.",
      standard:
        "Artificial General Intelligence (AGI) describes a hypothetical AI system capable of performing any intellectual task a human can — not just tasks it was specifically trained for, but arbitrary new tasks, using flexible reasoning and genuine transfer of knowledge across domains.\n\nNo such system exists. Every AI system deployed today is narrow AI: excellent within its training distribution, brittle outside it. When researchers or journalists describe an AI as having 'surpassed human intelligence,' they are always referring to performance on a specific benchmark — a structured test with known rules and measurable outcomes. Benchmark performance does not generalise to open-world general capability.\n\nThe question of when or whether AGI will arrive is genuinely uncertain and actively debated among researchers. What is not debated: today's large language models, regardless of how impressive their outputs can seem, are sophisticated pattern-matching systems, not general reasoning engines. They fail in predictable ways on novel tasks that require genuine reasoning from first principles, multi-step planning, or reliable factual recall.\n\nFor practical AI literacy: when you encounter claims that AI is becoming or has become generally intelligent, the useful question is 'intelligent at what, measured how, compared to what baseline?'",
      technical:
        "AGI is an informally defined target: an AI system achieving human-level or above performance across the full distribution of intellectual tasks, including novel tasks unseen during training. The absence of a precise formal definition makes AGI progress claims difficult to evaluate.\n\nCurrent LLMs exhibit in-context learning and zero-shot transfer that were not anticipated by classical learning theory. However, failure modes on compositional generalisation tasks (SCAN, ARC-AGI), multi-step reasoning, and out-of-distribution arithmetic suggest these capabilities are shallower than they appear. Proposed measures of general intelligence (g-factor analogues for AI, ARC benchmark) show large LLMs performing at human-novice levels, not expert-human levels, on tasks requiring genuine novel reasoning.\n\nKey architectural constraints: (1) context-window bounded working memory, (2) no persistent learning at inference time, (3) no reliable causal world model, (4) hallucination rates that do not approach zero. Whether scaling resolves these constraints is the central empirical question in the field. Current evidence suggests emergent capabilities appear at scale thresholds but systematic reasoning limitations remain across model families.",
    },
  },

  llm: {
    term: "Large Language Model (LLM)",
    glosses: {
      plain:
        "A Large Language Model — or LLM — is the technology behind tools like ChatGPT, Claude, and Gemini. The name tells you almost everything: it's a large model trained on language. Specifically, it learned from billions of pages of text — books, websites, code, articles — until it became very good at predicting what word comes next in a sentence.\n\nWhen you ask it a question, it doesn't look the answer up in a database. It generates a response word by word, each word chosen because it is the most likely continuation based on patterns in its training. That's why it sounds natural and fluent — and it's also why it can confidently write something completely wrong. Plausibility is not accuracy.\n\nThink of an LLM as the world's most sophisticated autocomplete. It has read almost everything ever written in its training data, and it is exceptionally good at writing things that sound like what a knowledgeable human would say. Whether those things are true is a separate question.",
      standard:
        "Large Language Models (LLMs) are neural networks trained on internet-scale text corpora to predict the next token in a sequence. This simple training objective — given everything so far, what comes next? — produces systems that can answer questions, write code, summarise documents, translate languages, and reason through problems with remarkable fluency.\n\nThe key mechanic: LLMs do not retrieve facts from a database. They generate responses by iteratively sampling the most likely next word given the context. This means their outputs are controlled by probability distributions learned from training data, not by logical rules or verified knowledge. A model can produce a confident, grammatically perfect, well-structured answer that is entirely false — because it learned the pattern of 'how confident answers about this topic tend to sound,' not the actual facts.\n\nThis is the root cause of 'hallucination' — a well-documented failure mode where LLMs generate plausible-sounding but factually incorrect content. The model has no internal fact-checker and no reliable way to distinguish what it knows from what it is confabulating. Fluency and confidence in tone are completely decoupled from factual accuracy.\n\nPractical habit: treat LLM output as a first draft from a knowledgeable-but-unreliable collaborator. The draft is often excellent. The facts need checking.",
      technical:
        "Large Language Models are autoregressive transformer architectures trained on token prediction objectives over web-scale corpora (10¹²–10¹³ tokens). Core components: tokenisation (BPE or SentencePiece), multi-head self-attention over a context window (typically 8k–1M tokens in current frontier models), feedforward sublayers, and a final unembedding + softmax projection to a probability distribution over the vocabulary.\n\nAt inference, output is sampled from p(x_t | x_<t) at each step, with temperature controlling distribution sharpness and top-p/top-k sampling truncating the tail. Greedy decoding (argmax) reduces diversity; high temperature increases creativity but also error rate.\n\nCapability emerges from pre-training scale (model parameters × training compute × data tokens) following approximately power-law scaling laws (Hoffmann et al., Chinchilla). Post-training alignment — instruction tuning (SFT) followed by RLHF or RLAIF — shapes the distribution toward helpful, harmless, honest outputs without substantially changing the base model's knowledge.\n\nKey limitations: (1) knowledge is frozen at training cutoff; (2) hallucination rates remain non-zero across all frontier models; (3) context-window constrained memory; (4) no reliable self-knowledge of confidence calibration. The model cannot distinguish between what it 'knows' (has strong training signal for) and what it is confabulating.",
    },
    analogy:
      "Like autocomplete that has read most of the internet — it predicts what word comes next, then again, and again, until a whole response appears. The writing looks human because it was trained on human writing. The facts need checking because plausibility and truth are not the same thing.",
  },

  hallucination: {
    term: "Hallucination",
    glosses: {
      plain:
        "AI hallucination is when a model makes something up and states it as fact — confidently, fluently, with no hint that it might be wrong. It might invent a scientific study that doesn't exist, quote a law incorrectly, give you a phone number that belongs to a different person, or describe an event that never happened. And it will do all of this in the same calm, helpful tone it uses when it's right.\n\nWhy does this happen? Because LLMs generate text by predicting what comes next based on patterns, not by looking up verified facts. The model learned 'how a credible answer about this topic tends to sound' — not 'what is actually true about this topic.' Plausibility is not accuracy.\n\nThe practical rule: never trust an LLM output for anything important without verifying it against a reliable source. The model can be an excellent starting point — a first draft, a brainstorm, a way to quickly understand a topic. But any specific claim — a date, a name, a statistic, a legal rule, a medical fact — must be confirmed independently.",
      standard:
        "Hallucination refers to the tendency of language models to generate content that sounds plausible and is stated confidently, but is factually incorrect or entirely fabricated. Examples include: inventing academic citations with believable-sounding titles and authors, misquoting laws or policies, generating realistic-seeming but false biographical details, or describing events that never occurred.\n\nHallucination is not a bug that will be patched away — it is a fundamental property of how LLMs work. The model generates text by predicting the most likely next token given everything before it. It has no separate verification mechanism, no connection to a live database of facts, and no reliable internal signal to distinguish what it genuinely 'knows' from what it is confabulating. Confidence in tone is completely decoupled from factual accuracy.\n\nThis has direct consequences for how you use AI tools. The more specific and verifiable a claim, the more important it is to check it: names, dates, statistics, citations, legal provisions, medical dosages, product specifications, and historical facts should all be verified against authoritative sources before being relied upon. The model is at its most reliable when generating or restructuring your own ideas — and at its most dangerous when being asked to supply facts it may never have had.\n\nA healthy habit: think of every AI output as a knowledgeable colleague's first-pass answer. Worth reading; not worth citing without checking.",
      technical:
        "Hallucination in language models refers to outputs with high model confidence but low factual accuracy — the model assigns high probability to false tokens. This is a consequence of optimising for next-token likelihood on training corpora rather than for factual accuracy.\n\nTwo main categories: (1) Closed-domain hallucination — incorrect outputs within a context window containing the relevant information (context misuse). (2) Open-domain hallucination — fabrication of facts not present in context or verifiable training data.\n\nMitigation strategies: Retrieval Augmented Generation (RAG) grounds generation in retrieved documents, reducing open-domain hallucination by providing the relevant context at inference time. Constitutional AI and RLHF reduce confident false assertions by shaping the output distribution toward epistemic humility. Calibration research attempts to align model confidence scores with empirical accuracy.\n\nHallucination rates remain non-trivial across all frontier models on domain-specific factual tasks. Evaluation is complicated by the difficulty of constructing ground-truth corpora for niche claims. Practical implication: no current LLM should be treated as a reliable oracle for specific factual claims; output should be verified against authoritative primary sources for any high-stakes use.",
    },
  },

  bias: {
    term: "Bias in AI",
    glosses: {
      plain:
        "AI bias means the model treats some groups of people differently — giving worse results, less accurate predictions, or worse outcomes to people from certain backgrounds. And unlike human bias, which at least has a face and can be held accountable, AI bias runs automatically, at scale, on millions of decisions.\n\nWhere does it come from? The training data. If a hiring model was trained on ten years of past hiring decisions, and those decisions reflected patterns of discrimination, the model will reproduce those patterns. If a medical model was trained mostly on data from one ethnicity, it will be less accurate for others. The model isn't prejudiced in the human sense — it just learned the patterns that were there.\n\nThe 'it's just math so it must be objective' argument is one of the most dangerous myths about AI. Math scales bias. It doesn't erase it. The fact that a decision was made by an algorithm doesn't make it fair — it just makes it faster, cheaper, and harder to challenge.",
      standard:
        "AI bias refers to systematic skew in a model's predictions or behaviour — producing worse outcomes for certain groups of people than others. The most studied forms include racial bias in facial recognition (higher error rates on darker skin tones), gender bias in hiring algorithms (downranking women for technical roles), and socioeconomic bias in loan approval models (unfairly penalising applicants based on ZIP code proxies).\n\nBias enters AI systems through multiple pathways. Historical data bias: if training data reflects past discrimination, the model learns to reproduce those patterns. Representation gaps: if certain populations are underrepresented in training data, accuracy is lower for those groups. Proxy variables: even when protected attributes (race, gender) are excluded from inputs, correlated features (ZIP code, name, school attended) can serve as proxies, laundering the bias through technically 'neutral' variables. Labelling bias: if human annotators have implicit biases, those biases enter the ground-truth labels the model optimises toward.\n\nThe 'AI is objective because it's mathematical' argument is one of the most consequential myths in technology. Algorithms scale whatever patterns are in their training data — bias included. A biased decision made manually affects one person at a time; a biased algorithm makes the same biased decision millions of times per day. The harms are larger, faster, and more difficult to contest because they appear to come from a neutral process.",
      technical:
        "Algorithmic bias refers to systematic disparities in model performance or output distribution across demographic subgroups, typically operationalised as differential prediction error (accuracy, precision, recall, AUROC) or differential exposure to beneficial/harmful outcomes.\n\nFormal fairness criteria are numerous and often incompatible: demographic parity (equal positive rate across groups), equalised odds (equal TPR and FPR), calibration (equal predicted probability accuracy), individual fairness (similar inputs mapped to similar outputs). Impossibility results (Chouldechova, 2017; Kleinberg et al., 2016) prove that certain fairness criteria cannot be simultaneously satisfied when base rates differ across groups — fairness is an inherently normative choice.\n\nBias enters through: (1) sampling bias in training distribution, (2) label bias from human annotators with implicit prejudice, (3) feature selection that preserves high-correlation proxies for protected attributes, (4) model architecture inductive biases, (5) feedback loops where biased predictions influence future training data. Mitigation techniques include pre-processing interventions (resampling, reweighting), in-processing constraints (fairness-regularised objectives), and post-processing calibration (threshold adjustment). No intervention is domain-neutral; appropriate choice depends on the downstream harm model.",
    },
  },

  prompt: {
    term: "Prompt Engineering",
    glosses: {
      plain:
        "A prompt is what you type to an AI. 'Prompt engineering' is the practice of crafting those inputs to get useful, accurate outputs. It sounds technical, but the core idea is simple: be specific about what you want, who you are, and what a good answer looks like.\n\nThe vague prompt 'write me a cover letter' produces a generic cover letter. The specific prompt 'write a cover letter for a software engineer with 5 years of Python experience applying for a remote data engineering role at a climate tech company — 3 paragraphs, professional but warm tone, lead with my expertise in processing large datasets' produces something you might actually use.\n\nThree things that almost always help: (1) Tell the AI who it is writing for. (2) Tell the AI what format you want. (3) Tell the AI what to avoid. The more context you give, the less the model has to guess — and guessing is where things go wrong.",
      standard:
        "Prompting is the act of providing a language model with the context and instructions that condition its output. Prompt engineering — deliberately crafting those inputs — is one of the highest-leverage skills for AI users. The difference between a vague prompt and a well-structured one can be the difference between a useless draft and a polished result.\n\nEffective prompts tend to include: a role or persona ('you are an expert science writer targeting a general audience'), a clear goal ('summarise this research paper in three paragraphs'), specific constraints ('no jargon, under 200 words, use active voice'), output format ('respond in bullet points'), and examples when relevant ('here's a sample of the tone I want').\n\nThe most common misconception about prompting is that there are 'magic phrases' that unlock better answers. There are not. What actually works is iteration and specificity. Start with a prompt, see where the output fails, identify which piece of context was missing, and add it. Repeat. Think of it as a conversation with a capable assistant who needs to be briefed, not a spell to be cast perfectly on the first try.\n\nEqually important: verify the output. A well-crafted prompt increases the chance of a useful response — it does not guarantee accuracy. Prompting skill does not substitute for critical evaluation of what the model produces.",
      technical:
        "A prompt is the input token sequence that conditions an LLM's output distribution at inference time. Prompt engineering is the empirical practice of selecting inputs that steer the model toward high-utility outputs within a fixed, trained model.\n\nKey techniques: (1) In-context learning (ICL) — providing k examples of input-output pairs prepends the inference with a demonstration distribution, shifting the model toward the demonstrated task. Few-shot prompting outperforms zero-shot on many structured tasks. (2) Chain-of-thought (CoT) — eliciting step-by-step reasoning ('let's think step by step') has been shown to substantially improve performance on multi-step arithmetic and logical reasoning tasks by externalising intermediate reasoning steps into the context window. (3) Role prompting — system-level persona conditioning shapes tone and register; evidence for substantial capability change is mixed. (4) Constitutional prompting — providing explicit criteria for self-evaluation enables the model to revise outputs against specified principles.\n\nContext-length effects: attention is not uniformly distributed across the context window. The 'lost in the middle' phenomenon describes degraded recall of information positioned mid-context in long inputs. Practical implication: critical constraints and examples should appear near the beginning or end of long prompts.\n\nPrompt injection is the adversarial counterpart: malicious instructions embedded in user content or retrieved data can override system-level instructions. This is an active security concern for any LLM-integrated application that processes untrusted input.",
    },
  },

  "context-window": {
    term: "Context Window",
    glosses: {
      plain:
        "The context window is the AI's working memory — the maximum amount of text it can 'see' at once. Everything outside the context window is invisible to the model. It cannot remember what you told it in a previous conversation (unless that information is re-provided) and it cannot remember what's in a long document if that document exceeds the window limit.\n\nA practical consequence: if you paste a very long document and ask the model to summarise it, the quality of the summary can degrade depending on what falls in the middle. Research has found that LLMs pay more attention to the beginning and end of their context window — information buried in the middle is more likely to be missed or misrepresented.\n\nThe fix: for long documents, break them into sections and work through each one. Ask targeted questions rather than 'summarise everything.' And never assume the model 'remembered' something from a previous session — always re-provide important context.",
      standard:
        "The context window defines the maximum amount of text a language model can process in a single interaction — both the input you provide and the output it generates. Modern frontier models have context windows ranging from ~8,000 to ~1,000,000 tokens (roughly 6,000 to 750,000 words). Everything outside the window is invisible to the model at that point.\n\nContext windows have two practical consequences. First, there is a hard knowledge boundary: for conversations or documents longer than the context window, earlier content must be either summarised, discarded, or re-provided. The model has no memory of past sessions by default. Second, attention is not uniform within the window: research has documented the 'lost in the middle' phenomenon, where retrieval of information positioned in the middle of long contexts is significantly less reliable than retrieval of information near the beginning or end.\n\nFor users: (1) Always re-provide critical context at the start of each new session; (2) For very long documents, prefer targeted queries ('what does the contract say about termination clauses?') over sweeping summaries; (3) When summarising long content, consider breaking it into sections and summarising each one separately.",
      technical:
        "The context window is the maximum token sequence length the model can process in a single forward pass, encompassing both the prompt and the generated completion. Architectural context limits are set by the attention mechanism's complexity (O(n²) in standard self-attention) and positional encoding scheme.\n\nModern approaches to extending context: (1) Efficient attention variants (Longformer, FlashAttention, linear attention approximations) reduce quadratic attention cost. (2) Positional encoding extrapolation (RoPE, ALiBi) enables inference beyond training context lengths with varying fidelity. (3) RAG replaces in-context storage of long documents with retrieval at inference time.\n\nThe 'lost in the middle' phenomenon (Liu et al., 2023) documents a U-shaped recall curve within long contexts: performance degrades for information positioned mid-context relative to prefix and suffix positions. The mechanism is hypothesised to relate to attention sink effects and proximity bias in autoregressive attention patterns.\n\nPractical deployment implications: (1) RAG is often preferable to long-context retrieval for precise factual lookup due to more reliable retrieval mechanics; (2) Multi-turn context management (summarisation, selective retention) is required for long-horizon agentic tasks; (3) Prompt positioning matters — high-value constraints should appear at position-salient locations (beginning of system prompt, end of user turn).",
    },
  },

  "ai-accountability": {
    term: "Accountability in AI Systems",
    glosses: {
      plain:
        "When an AI system makes a decision that harms someone — denying a loan, misdiagnosing an illness, wrongly flagging a face — someone needs to be accountable. But who?\n\nThe answer is: the people and organisations who built, deployed, and chose to rely on the system. The model cannot be held responsible. It doesn't make choices; it produces outputs. The humans who decided to use those outputs, how to deploy the system, which safeguards to include, and whose interests to protect — those are the people who bear responsibility.\n\n'It was the algorithm's decision' is not a valid excuse. If you deploy an AI to make consequential decisions about people's lives, you are responsible for the quality and fairness of those decisions. The algorithm is a tool you chose. You are accountable for how you use it.",
      standard:
        "When AI systems make consequential errors — wrongly denying a loan, incorrectly flagging a suspect, miscategorising a medical case — the question of accountability is both ethical and legal. A key principle: models cannot bear accountability. Accountability for automated decisions rests with the humans and institutions who designed, deployed, and maintained the system.\n\nThis means several things in practice. The organisation that deployed an AI screening tool is responsible for auditing it for fairness before deployment — not just assuming it works. The team that chose training data is responsible for the biases encoded in it. The manager who relied on AI output to make a hiring decision is responsible for that decision, not shielded by the automation.\n\nA recurring failure pattern is 'accountability laundering' — using algorithmic processes to diffuse responsibility across so many people and systems that no one remains clearly accountable when harm occurs. The EU AI Act, the FTC's AI guidance, and emerging case law are all working to close this gap by requiring transparency, auditability, and human oversight for high-risk AI deployments.\n\nFor anyone using AI in professional contexts: document your AI use, retain human review for consequential decisions, and be prepared to explain — and stand behind — any AI-assisted outcome.",
      technical:
        "Accountability in AI systems involves the assignment of responsibility for outcomes across the sociotechnical system: model developers, data curators, system integrators, deployers, and end users. Meaningful accountability requires traceability — the ability to reconstruct how a specific output was produced — and contestability — the ability of affected parties to challenge and seek redress for AI-driven decisions.\n\nLegal frameworks diverge: EU AI Act (2024) establishes risk tiers with mandatory conformity assessment, human oversight requirements, and post-market monitoring obligations for high-risk AI applications. US executive guidance focuses on sector-specific principles without binding horizontal legislation. Both frameworks establish that deployers bear primary legal responsibility for AI-driven decisions affecting individuals.\n\nTechnical requirements for accountable AI: (1) Audit trails — logs sufficient to reconstruct decision pathways; (2) Explainability — outputs interpretable to affected individuals and oversight bodies (SHAP, LIME, post-hoc rationalisation); (3) Monitoring — distribution shift detection, performance tracking across demographic subgroups, anomaly alerting; (4) Rollback capability — mechanisms to disable the system or revert to a prior version on detection of harmful drift.\n\nThe 'black box' problem — where model internals are opaque even to developers — creates accountability gaps that explainability methods only partially close. There is active tension between model performance (often enhanced by opacity) and regulatory requirements for interpretability.",
    },
  },

  "data-privacy": {
    term: "Data Privacy and AI",
    glosses: {
      plain:
        "Every time you use an AI tool, you are also sharing data. The question is: what data, with whom, and for how long?\n\nSome AI tools are trained on user conversations. Some store everything indefinitely. Some share data with third parties. Most of this is disclosed in privacy policies that almost no one reads. That's a problem — because your conversations with an AI might contain sensitive information: medical symptoms, work documents, personal relationships, financial details.\n\nThe practical habit: before using an AI tool for anything sensitive, check whether conversations are stored, whether they're used for training, and whether you can opt out. For truly sensitive work, use tools with explicit data-retention controls or use them in enterprise/private-deployment mode where data stays within your organisation.",
      standard:
        "AI tools collect and use data in ways that warrant careful consideration, particularly for professional and personal sensitive information. The relevant questions are: Is my input stored? For how long? Is it used to retrain the model? Who has access to it? Can I delete it?\n\nFor consumer AI tools, the default in many cases is that conversations may be reviewed by employees for safety or quality purposes and may be used to improve models. Business versions of the same tools often offer stronger guarantees: data is not retained, is not used for training, and is stored within specific jurisdictions.\n\nSeveral specific risks: (1) Sensitive professional data — attaching confidential business documents to an AI query may share that content with the AI provider. (2) Personal health information — asking medical questions may create stored records of sensitive conditions. (3) Legal privilege — attorney-client privileged communications should never be shared with AI tools without legal guidance. (4) FERPA and HIPAA — regulated student and health information may not be shareable with AI tools under standard consumer terms.\n\nThe underlying principle: 'free' AI tools are often monetised through data. The value exchange is worth understanding before the exchange happens.",
      technical:
        "AI data privacy concerns span the full model lifecycle: training data collection (consent, provenance, personal data inclusion), inference-time data handling (input retention, logging, third-party sharing), and model memory (whether models encode personally identifiable information in weights).\n\nTraining data privacy: large-scale web-crawled corpora frequently contain personal information (names, addresses, email content, social media posts) often collected without explicit consent. Memorisation research (Carlini et al., 2021) demonstrates that LLMs can reproduce verbatim training data under targeted extraction attacks, including PII. Differential privacy training provides formal privacy guarantees but typically degrades model utility.\n\nInference privacy: most commercial LLMs log query-response pairs. Terms of service determine retention policy, training use, and access controls. Enterprise agreements typically offer stronger guarantees (no training use, data residency, deletion on request). Privacy-preserving inference (homomorphic encryption, secure multi-party computation) remains computationally prohibitive for large-scale deployment.\n\nRegulatory landscape: GDPR Article 22 restricts solely automated decision-making affecting individuals; right to erasure is complicated by model memorisation. CCPA provides similar rights for California residents. The EU AI Act introduces data governance requirements for high-risk AI training data. The tension between regulatory right-to-erasure and the cost of model unlearning (machine unlearning research is an active area) remains unresolved.",
    },
  },

  "ai-augmentation": {
    term: "AI as Augmentation, Not Replacement",
    glosses: {
      plain:
        "There's a widespread fear that AI will take everyone's job. The reality is more complicated — and for most people in most jobs today, more reassuring.\n\nAI is very good at certain things: drafting, summarising, classifying, pattern-matching in data, generating variations on existing content. It is poor at other things: genuine creativity, moral judgment, building relationships, navigating novel situations, taking responsibility for outcomes. Most jobs require some of both.\n\nThe historical pattern is that automation eliminates specific tasks within jobs, not entire jobs wholesale. The spreadsheet eliminated some bookkeeping tasks but created the accountant as we know the role today. Email eliminated some administrative tasks but created new communication demands. AI is following a similar pattern: it handles the drafting, you do the judgment. It handles the search, you do the synthesis. Learning to work with AI — to use it to amplify your output rather than replace your judgment — is the practical skill of this decade.",
      standard:
        "The question of AI's impact on employment is real and not fully resolved — but the 'AI will replace all jobs' narrative overstates the case and misrepresents the pattern of how automation has historically worked.\n\nCurrent AI excels at tasks involving pattern recognition in large data, generating variations on existing content, and routine classification. It struggles with tasks requiring genuine contextual judgment, accountability for outcomes, novel problem-solving outside its training distribution, and relationship-building. Most occupations contain a mix of both kinds of tasks.\n\nHistorical automation precedents suggest displacement of specific tasks, not entire occupations. The spreadsheet automated calculation but created the financial analyst role as we know it. Word processing eliminated typing pools but expanded the scope of writing professionals. ATMs did not eliminate bank tellers — branch numbers remained stable while teller roles shifted toward relationship banking. In each case, the humans who thrived were those who adapted: learning to work with the new tool, focusing on the judgment and relationship tasks it could not perform.\n\nThe practical implication for your career: identify which tasks in your role AI can handle, use it for those, and invest in the judgment, communication, and relationship skills that differentiate you from a model. The risk is not replacement — it's irrelevance for those who don't adapt, and leverage for those who do.",
      technical:
        "The economic analysis of AI's labour market impact draws on task-based models of occupational change. The relevant distinction is between automation of tasks versus displacement of occupations. AI augments workers by lowering the cost of certain task inputs (language generation, pattern classification), shifting the marginal value of complementary tasks (judgment, creativity, oversight, relationship management).\n\nEmpirical evidence on LLM labour market effects is preliminary but developing: (1) BCG/Harvard field experiment (2023) found GPT-4 raised worker productivity on knowledge work tasks 12.2% on average. (2) Goldman Sachs modelling projects 26% of US work tasks could be automated by current AI. (3) Labour market data shows growing demand for AI oversight, prompt engineering, and AI-adjacent roles, offsetting some displacement.\n\nThe 'task displacement, occupation evolution' pattern is consistent with historical automation waves (mechanisation, computerisation). However, the pace of change and breadth of cognitive task coverage distinguish this wave. Key variables determining individual exposure: (1) routine vs. non-routine cognitive content, (2) social and relational task weight, (3) physical task weight, (4) degree of novelty required. Workers with high social, physical, or novel-reasoning task loads face lower immediate substitution risk.",
    },
  },
};
